// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/controlplane.proto

package controlplane

import (
	controller "github.com/kcore/kcore/api/controller"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollmentTokenScope int32

const (
	EnrollmentTokenScope_ENROLLMENT_TOKEN_SCOPE_UNSPECIFIED    EnrollmentTokenScope = 0
	EnrollmentTokenScope_ENROLLMENT_TOKEN_SCOPE_NODE_BOOTSTRAP EnrollmentTokenScope = 1
)

// Enum value maps for EnrollmentTokenScope.
var (
	EnrollmentTokenScope_name = map[int32]string{
		0: "ENROLLMENT_TOKEN_SCOPE_UNSPECIFIED",
		1: "ENROLLMENT_TOKEN_SCOPE_NODE_BOOTSTRAP",
	}
	EnrollmentTokenScope_value = map[string]int32{
		"ENROLLMENT_TOKEN_SCOPE_UNSPECIFIED":    0,
		"ENROLLMENT_TOKEN_SCOPE_NODE_BOOTSTRAP": 1,
	}
)

func (x EnrollmentTokenScope) Enum() *EnrollmentTokenScope {
	p := new(EnrollmentTokenScope)
	*p = x
	return p
}

func (x EnrollmentTokenScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrollmentTokenScope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_controlplane_proto_enumTypes[0].Descriptor()
}

func (EnrollmentTokenScope) Type() protoreflect.EnumType {
	return &file_proto_controlplane_proto_enumTypes[0]
}

func (x EnrollmentTokenScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrollmentTokenScope.Descriptor instead.
func (EnrollmentTokenScope) EnumDescriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{0}
}

type InstallPhase int32

const (
	InstallPhase_INSTALL_PHASE_UNSPECIFIED      InstallPhase = 0
	InstallPhase_INSTALL_PHASE_BOOTED_LIVE      InstallPhase = 1
	InstallPhase_INSTALL_PHASE_DISK_PARTITIONED InstallPhase = 2
	InstallPhase_INSTALL_PHASE_OS_WRITTEN       InstallPhase = 3
	InstallPhase_INSTALL_PHASE_REBOOTED         InstallPhase = 4
	InstallPhase_INSTALL_PHASE_ENROLLED         InstallPhase = 5
	InstallPhase_INSTALL_PHASE_READY            InstallPhase = 6
	InstallPhase_INSTALL_PHASE_FAILED           InstallPhase = 7
)

// Enum value maps for InstallPhase.
var (
	InstallPhase_name = map[int32]string{
		0: "INSTALL_PHASE_UNSPECIFIED",
		1: "INSTALL_PHASE_BOOTED_LIVE",
		2: "INSTALL_PHASE_DISK_PARTITIONED",
		3: "INSTALL_PHASE_OS_WRITTEN",
		4: "INSTALL_PHASE_REBOOTED",
		5: "INSTALL_PHASE_ENROLLED",
		6: "INSTALL_PHASE_READY",
		7: "INSTALL_PHASE_FAILED",
	}
	InstallPhase_value = map[string]int32{
		"INSTALL_PHASE_UNSPECIFIED":      0,
		"INSTALL_PHASE_BOOTED_LIVE":      1,
		"INSTALL_PHASE_DISK_PARTITIONED": 2,
		"INSTALL_PHASE_OS_WRITTEN":       3,
		"INSTALL_PHASE_REBOOTED":         4,
		"INSTALL_PHASE_ENROLLED":         5,
		"INSTALL_PHASE_READY":            6,
		"INSTALL_PHASE_FAILED":           7,
	}
)

func (x InstallPhase) Enum() *InstallPhase {
	p := new(InstallPhase)
	*p = x
	return p
}

func (x InstallPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_controlplane_proto_enumTypes[1].Descriptor()
}

func (InstallPhase) Type() protoreflect.EnumType {
	return &file_proto_controlplane_proto_enumTypes[1]
}

func (x InstallPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallPhase.Descriptor instead.
func (InstallPhase) EnumDescriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{1}
}

type ApplyNodeNixConfigRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	NodeId        string                            `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Config        *controller.ApplyNixConfigRequest `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyNodeNixConfigRequest) Reset() {
	*x = ApplyNodeNixConfigRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyNodeNixConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyNodeNixConfigRequest) ProtoMessage() {}

func (x *ApplyNodeNixConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyNodeNixConfigRequest.ProtoReflect.Descriptor instead.
func (*ApplyNodeNixConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyNodeNixConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ApplyNodeNixConfigRequest) GetConfig() *controller.ApplyNixConfigRequest {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateEnrollmentTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         EnrollmentTokenScope   `protobuf:"varint,1,opt,name=scope,proto3,enum=kcore.controlplane.EnrollmentTokenScope" json:"scope,omitempty"`
	AllowedLabels []string               `protobuf:"bytes,2,rep,name=allowed_labels,json=allowedLabels,proto3" json:"allowed_labels,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnrollmentTokenRequest) Reset() {
	*x = CreateEnrollmentTokenRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentTokenRequest) ProtoMessage() {}

func (x *CreateEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEnrollmentTokenRequest) GetScope() EnrollmentTokenScope {
	if x != nil {
		return x.Scope
	}
	return EnrollmentTokenScope_ENROLLMENT_TOKEN_SCOPE_UNSPECIFIED
}

func (x *CreateEnrollmentTokenRequest) GetAllowedLabels() []string {
	if x != nil {
		return x.AllowedLabels
	}
	return nil
}

func (x *CreateEnrollmentTokenRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateEnrollmentTokenRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateEnrollmentTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenSecret   string                 `protobuf:"bytes,2,opt,name=token_secret,json=tokenSecret,proto3" json:"token_secret,omitempty"` // Returned only once.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnrollmentTokenResponse) Reset() {
	*x = CreateEnrollmentTokenResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentTokenResponse) ProtoMessage() {}

func (x *CreateEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEnrollmentTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *CreateEnrollmentTokenResponse) GetTokenSecret() string {
	if x != nil {
		return x.TokenSecret
	}
	return ""
}

type RevokeEnrollmentTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeEnrollmentTokenRequest) Reset() {
	*x = RevokeEnrollmentTokenRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeEnrollmentTokenRequest) ProtoMessage() {}

func (x *RevokeEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeEnrollmentTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type RevokeEnrollmentTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeEnrollmentTokenResponse) Reset() {
	*x = RevokeEnrollmentTokenResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeEnrollmentTokenResponse) ProtoMessage() {}

func (x *RevokeEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeEnrollmentTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EnrollmentTokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Scope         EnrollmentTokenScope   `protobuf:"varint,2,opt,name=scope,proto3,enum=kcore.controlplane.EnrollmentTokenScope" json:"scope,omitempty"`
	AllowedLabels []string               `protobuf:"bytes,3,rep,name=allowed_labels,json=allowedLabels,proto3" json:"allowed_labels,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Revoked       bool                   `protobuf:"varint,5,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentTokenInfo) Reset() {
	*x = EnrollmentTokenInfo{}
	mi := &file_proto_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentTokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentTokenInfo) ProtoMessage() {}

func (x *EnrollmentTokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentTokenInfo.ProtoReflect.Descriptor instead.
func (*EnrollmentTokenInfo) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollmentTokenInfo) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *EnrollmentTokenInfo) GetScope() EnrollmentTokenScope {
	if x != nil {
		return x.Scope
	}
	return EnrollmentTokenScope_ENROLLMENT_TOKEN_SCOPE_UNSPECIFIED
}

func (x *EnrollmentTokenInfo) GetAllowedLabels() []string {
	if x != nil {
		return x.AllowedLabels
	}
	return nil
}

func (x *EnrollmentTokenInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *EnrollmentTokenInfo) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *EnrollmentTokenInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListEnrollmentTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentTokensRequest) Reset() {
	*x = ListEnrollmentTokensRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentTokensRequest) ProtoMessage() {}

func (x *ListEnrollmentTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentTokensRequest.ProtoReflect.Descriptor instead.
func (*ListEnrollmentTokensRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{6}
}

type ListEnrollmentTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*EnrollmentTokenInfo `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentTokensResponse) Reset() {
	*x = ListEnrollmentTokensResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentTokensResponse) ProtoMessage() {}

func (x *ListEnrollmentTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentTokensResponse.ProtoReflect.Descriptor instead.
func (*ListEnrollmentTokensResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *ListEnrollmentTokensResponse) GetTokens() []*EnrollmentTokenInfo {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type BootstrapNetworkDefaults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkMap    map[string]string      `protobuf:"bytes,1,rep,name=network_map,json=networkMap,proto3" json:"network_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapNetworkDefaults) Reset() {
	*x = BootstrapNetworkDefaults{}
	mi := &file_proto_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapNetworkDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapNetworkDefaults) ProtoMessage() {}

func (x *BootstrapNetworkDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapNetworkDefaults.ProtoReflect.Descriptor instead.
func (*BootstrapNetworkDefaults) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *BootstrapNetworkDefaults) GetNetworkMap() map[string]string {
	if x != nil {
		return x.NetworkMap
	}
	return nil
}

type BootstrapStorageDefaults struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DefaultDriver    string                 `protobuf:"bytes,1,opt,name=default_driver,json=defaultDriver,proto3" json:"default_driver,omitempty"`
	DriverParameters map[string]string      `protobuf:"bytes,2,rep,name=driver_parameters,json=driverParameters,proto3" json:"driver_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BootstrapStorageDefaults) Reset() {
	*x = BootstrapStorageDefaults{}
	mi := &file_proto_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapStorageDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapStorageDefaults) ProtoMessage() {}

func (x *BootstrapStorageDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapStorageDefaults.ProtoReflect.Descriptor instead.
func (*BootstrapStorageDefaults) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *BootstrapStorageDefaults) GetDefaultDriver() string {
	if x != nil {
		return x.DefaultDriver
	}
	return ""
}

func (x *BootstrapStorageDefaults) GetDriverParameters() map[string]string {
	if x != nil {
		return x.DriverParameters
	}
	return nil
}

type GetBootstrapConfigRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`
	NodeHostname    string                 `protobuf:"bytes,2,opt,name=node_hostname,json=nodeHostname,proto3" json:"node_hostname,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBootstrapConfigRequest) Reset() {
	*x = GetBootstrapConfigRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootstrapConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapConfigRequest) ProtoMessage() {}

func (x *GetBootstrapConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapConfigRequest.ProtoReflect.Descriptor instead.
func (*GetBootstrapConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *GetBootstrapConfigRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *GetBootstrapConfigRequest) GetNodeHostname() string {
	if x != nil {
		return x.NodeHostname
	}
	return ""
}

type GetBootstrapConfigResponse struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	ControllerAddress        string                    `protobuf:"bytes,1,opt,name=controller_address,json=controllerAddress,proto3" json:"controller_address,omitempty"`
	CaBundlePem              []byte                    `protobuf:"bytes,2,opt,name=ca_bundle_pem,json=caBundlePem,proto3" json:"ca_bundle_pem,omitempty"`
	Network                  *BootstrapNetworkDefaults `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Storage                  *BootstrapStorageDefaults `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	HeartbeatIntervalSeconds int32                     `protobuf:"varint,5,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetBootstrapConfigResponse) Reset() {
	*x = GetBootstrapConfigResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootstrapConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootstrapConfigResponse) ProtoMessage() {}

func (x *GetBootstrapConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootstrapConfigResponse.ProtoReflect.Descriptor instead.
func (*GetBootstrapConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *GetBootstrapConfigResponse) GetControllerAddress() string {
	if x != nil {
		return x.ControllerAddress
	}
	return ""
}

func (x *GetBootstrapConfigResponse) GetCaBundlePem() []byte {
	if x != nil {
		return x.CaBundlePem
	}
	return nil
}

func (x *GetBootstrapConfigResponse) GetNetwork() *BootstrapNetworkDefaults {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *GetBootstrapConfigResponse) GetStorage() *BootstrapStorageDefaults {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *GetBootstrapConfigResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type NodeMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ReportedAddress string                 `protobuf:"bytes,2,opt,name=reported_address,json=reportedAddress,proto3" json:"reported_address,omitempty"`
	Labels          []string               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	OsVersion       string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Kernel          string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	MachineId       string                 `protobuf:"bytes,6,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeMetadata) Reset() {
	*x = NodeMetadata{}
	mi := &file_proto_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadata) ProtoMessage() {}

func (x *NodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadata.ProtoReflect.Descriptor instead.
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *NodeMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeMetadata) GetReportedAddress() string {
	if x != nil {
		return x.ReportedAddress
	}
	return ""
}

func (x *NodeMetadata) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NodeMetadata) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *NodeMetadata) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *NodeMetadata) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type EnrollNodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`
	CsrPem          []byte                 `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	Metadata        *NodeMetadata          `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollNodeRequest) Reset() {
	*x = EnrollNodeRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollNodeRequest) ProtoMessage() {}

func (x *EnrollNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollNodeRequest.ProtoReflect.Descriptor instead.
func (*EnrollNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *EnrollNodeRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollNodeRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EnrollNodeRequest) GetMetadata() *NodeMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EnrollNodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SignedCertPem     []byte                 `protobuf:"bytes,2,opt,name=signed_cert_pem,json=signedCertPem,proto3" json:"signed_cert_pem,omitempty"`
	CaBundlePem       []byte                 `protobuf:"bytes,3,opt,name=ca_bundle_pem,json=caBundlePem,proto3" json:"ca_bundle_pem,omitempty"`
	ControllerAddress string                 `protobuf:"bytes,4,opt,name=controller_address,json=controllerAddress,proto3" json:"controller_address,omitempty"`
	CertExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=cert_expires_at,json=certExpiresAt,proto3" json:"cert_expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnrollNodeResponse) Reset() {
	*x = EnrollNodeResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollNodeResponse) ProtoMessage() {}

func (x *EnrollNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollNodeResponse.ProtoReflect.Descriptor instead.
func (*EnrollNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *EnrollNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EnrollNodeResponse) GetSignedCertPem() []byte {
	if x != nil {
		return x.SignedCertPem
	}
	return nil
}

func (x *EnrollNodeResponse) GetCaBundlePem() []byte {
	if x != nil {
		return x.CaBundlePem
	}
	return nil
}

func (x *EnrollNodeResponse) GetControllerAddress() string {
	if x != nil {
		return x.ControllerAddress
	}
	return ""
}

func (x *EnrollNodeResponse) GetCertExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CertExpiresAt
	}
	return nil
}

type RotateNodeCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateNodeCertificateRequest) Reset() {
	*x = RotateNodeCertificateRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateNodeCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateNodeCertificateRequest) ProtoMessage() {}

func (x *RotateNodeCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateNodeCertificateRequest.ProtoReflect.Descriptor instead.
func (*RotateNodeCertificateRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{15}
}

func (x *RotateNodeCertificateRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RotateNodeCertificateRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type RotateNodeCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedCertPem []byte                 `protobuf:"bytes,1,opt,name=signed_cert_pem,json=signedCertPem,proto3" json:"signed_cert_pem,omitempty"`
	CaBundlePem   []byte                 `protobuf:"bytes,2,opt,name=ca_bundle_pem,json=caBundlePem,proto3" json:"ca_bundle_pem,omitempty"`
	CertExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=cert_expires_at,json=certExpiresAt,proto3" json:"cert_expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateNodeCertificateResponse) Reset() {
	*x = RotateNodeCertificateResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateNodeCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateNodeCertificateResponse) ProtoMessage() {}

func (x *RotateNodeCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateNodeCertificateResponse.ProtoReflect.Descriptor instead.
func (*RotateNodeCertificateResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{16}
}

func (x *RotateNodeCertificateResponse) GetSignedCertPem() []byte {
	if x != nil {
		return x.SignedCertPem
	}
	return nil
}

func (x *RotateNodeCertificateResponse) GetCaBundlePem() []byte {
	if x != nil {
		return x.CaBundlePem
	}
	return nil
}

func (x *RotateNodeCertificateResponse) GetCertExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CertExpiresAt
	}
	return nil
}

type ReportInstallStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MachineId     string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Phase         InstallPhase           `protobuf:"varint,3,opt,name=phase,proto3,enum=kcore.controlplane.InstallPhase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInstallStatusRequest) Reset() {
	*x = ReportInstallStatusRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInstallStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInstallStatusRequest) ProtoMessage() {}

func (x *ReportInstallStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInstallStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportInstallStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{17}
}

func (x *ReportInstallStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportInstallStatusRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ReportInstallStatusRequest) GetPhase() InstallPhase {
	if x != nil {
		return x.Phase
	}
	return InstallPhase_INSTALL_PHASE_UNSPECIFIED
}

func (x *ReportInstallStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportInstallStatusRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type ReportInstallStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInstallStatusResponse) Reset() {
	*x = ReportInstallStatusResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInstallStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInstallStatusResponse) ProtoMessage() {}

func (x *ReportInstallStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInstallStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportInstallStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{18}
}

func (x *ReportInstallStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetInstallStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MachineId     string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstallStatusRequest) Reset() {
	*x = GetInstallStatusRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallStatusRequest) ProtoMessage() {}

func (x *GetInstallStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallStatusRequest.ProtoReflect.Descriptor instead.
func (*GetInstallStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{19}
}

func (x *GetInstallStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetInstallStatusRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type InstallStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MachineId     string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Phase         InstallPhase           `protobuf:"varint,3,opt,name=phase,proto3,enum=kcore.controlplane.InstallPhase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallStatus) Reset() {
	*x = InstallStatus{}
	mi := &file_proto_controlplane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallStatus) ProtoMessage() {}

func (x *InstallStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallStatus.ProtoReflect.Descriptor instead.
func (*InstallStatus) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{20}
}

func (x *InstallStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InstallStatus) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *InstallStatus) GetPhase() InstallPhase {
	if x != nil {
		return x.Phase
	}
	return InstallPhase_INSTALL_PHASE_UNSPECIFIED
}

func (x *InstallStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstallStatus) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type GetInstallStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *InstallStatus         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstallStatusResponse) Reset() {
	*x = GetInstallStatusResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallStatusResponse) ProtoMessage() {}

func (x *GetInstallStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallStatusResponse.ProtoReflect.Descriptor instead.
func (*GetInstallStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{21}
}

func (x *GetInstallStatusResponse) GetStatus() *InstallStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListInstallStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstallStatusRequest) Reset() {
	*x = ListInstallStatusRequest{}
	mi := &file_proto_controlplane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstallStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstallStatusRequest) ProtoMessage() {}

func (x *ListInstallStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstallStatusRequest.ProtoReflect.Descriptor instead.
func (*ListInstallStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{22}
}

type ListInstallStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*InstallStatus       `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstallStatusResponse) Reset() {
	*x = ListInstallStatusResponse{}
	mi := &file_proto_controlplane_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstallStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstallStatusResponse) ProtoMessage() {}

func (x *ListInstallStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstallStatusResponse.ProtoReflect.Descriptor instead.
func (*ListInstallStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_proto_rawDescGZIP(), []int{23}
}

func (x *ListInstallStatusResponse) GetStatuses() []*InstallStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_proto_controlplane_proto protoreflect.FileDescriptor

const file_proto_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x18proto/controlplane.proto\x12\x12kcore.controlplane\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16proto/controller.proto\"u\n" +
	"\x19ApplyNodeNixConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12?\n" +
	"\x06config\x18\x02 \x01(\v2'.kcore.controller.ApplyNixConfigRequestR\x06config\"\xe2\x01\n" +
	"\x1cCreateEnrollmentTokenRequest\x12>\n" +
	"\x05scope\x18\x01 \x01(\x0e2(.kcore.controlplane.EnrollmentTokenScopeR\x05scope\x12%\n" +
	"\x0eallowed_labels\x18\x02 \x03(\tR\rallowedLabels\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"]\n" +
	"\x1dCreateEnrollmentTokenResponse\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12!\n" +
	"\ftoken_secret\x18\x02 \x01(\tR\vtokenSecret\"9\n" +
	"\x1cRevokeEnrollmentTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"9\n" +
	"\x1dRevokeEnrollmentTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x02\n" +
	"\x13EnrollmentTokenInfo\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12>\n" +
	"\x05scope\x18\x02 \x01(\x0e2(.kcore.controlplane.EnrollmentTokenScopeR\x05scope\x12%\n" +
	"\x0eallowed_labels\x18\x03 \x03(\tR\rallowedLabels\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\arevoked\x18\x05 \x01(\bR\arevoked\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\x1d\n" +
	"\x1bListEnrollmentTokensRequest\"_\n" +
	"\x1cListEnrollmentTokensResponse\x12?\n" +
	"\x06tokens\x18\x01 \x03(\v2'.kcore.controlplane.EnrollmentTokenInfoR\x06tokens\"\xb8\x01\n" +
	"\x18BootstrapNetworkDefaults\x12]\n" +
	"\vnetwork_map\x18\x01 \x03(\v2<.kcore.controlplane.BootstrapNetworkDefaults.NetworkMapEntryR\n" +
	"networkMap\x1a=\n" +
	"\x0fNetworkMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x01\n" +
	"\x18BootstrapStorageDefaults\x12%\n" +
	"\x0edefault_driver\x18\x01 \x01(\tR\rdefaultDriver\x12o\n" +
	"\x11driver_parameters\x18\x02 \x03(\v2B.kcore.controlplane.BootstrapStorageDefaults.DriverParametersEntryR\x10driverParameters\x1aC\n" +
	"\x15DriverParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x19GetBootstrapConfigRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12#\n" +
	"\rnode_hostname\x18\x02 \x01(\tR\fnodeHostname\"\xbd\x02\n" +
	"\x1aGetBootstrapConfigResponse\x12-\n" +
	"\x12controller_address\x18\x01 \x01(\tR\x11controllerAddress\x12\"\n" +
	"\rca_bundle_pem\x18\x02 \x01(\fR\vcaBundlePem\x12F\n" +
	"\anetwork\x18\x03 \x01(\v2,.kcore.controlplane.BootstrapNetworkDefaultsR\anetwork\x12F\n" +
	"\astorage\x18\x04 \x01(\v2,.kcore.controlplane.BootstrapStorageDefaultsR\astorage\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x05 \x01(\x05R\x18heartbeatIntervalSeconds\"\xc3\x01\n" +
	"\fNodeMetadata\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12)\n" +
	"\x10reported_address\x18\x02 \x01(\tR\x0freportedAddress\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x06 \x01(\tR\tmachineId\"\x95\x01\n" +
	"\x11EnrollNodeRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\x12<\n" +
	"\bmetadata\x18\x03 \x01(\v2 .kcore.controlplane.NodeMetadataR\bmetadata\"\xec\x01\n" +
	"\x12EnrollNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12&\n" +
	"\x0fsigned_cert_pem\x18\x02 \x01(\fR\rsignedCertPem\x12\"\n" +
	"\rca_bundle_pem\x18\x03 \x01(\fR\vcaBundlePem\x12-\n" +
	"\x12controller_address\x18\x04 \x01(\tR\x11controllerAddress\x12B\n" +
	"\x0fcert_expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rcertExpiresAt\"P\n" +
	"\x1cRotateNodeCertificateRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\"\xaf\x01\n" +
	"\x1dRotateNodeCertificateResponse\x12&\n" +
	"\x0fsigned_cert_pem\x18\x01 \x01(\fR\rsignedCertPem\x12\"\n" +
	"\rca_bundle_pem\x18\x02 \x01(\fR\vcaBundlePem\x12B\n" +
	"\x0fcert_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rcertExpiresAt\"\xe3\x01\n" +
	"\x1aReportInstallStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x126\n" +
	"\x05phase\x18\x03 \x01(\x0e2 .kcore.controlplane.InstallPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"7\n" +
	"\x1bReportInstallStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x17GetInstallStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\"\xd6\x01\n" +
	"\rInstallStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x126\n" +
	"\x05phase\x18\x03 \x01(\x0e2 .kcore.controlplane.InstallPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"U\n" +
	"\x18GetInstallStatusResponse\x129\n" +
	"\x06status\x18\x01 \x01(\v2!.kcore.controlplane.InstallStatusR\x06status\"\x1a\n" +
	"\x18ListInstallStatusRequest\"Z\n" +
	"\x19ListInstallStatusResponse\x12=\n" +
	"\bstatuses\x18\x01 \x03(\v2!.kcore.controlplane.InstallStatusR\bstatuses*i\n" +
	"\x14EnrollmentTokenScope\x12&\n" +
	"\"ENROLLMENT_TOKEN_SCOPE_UNSPECIFIED\x10\x00\x12)\n" +
	"%ENROLLMENT_TOKEN_SCOPE_NODE_BOOTSTRAP\x10\x01*\xf9\x01\n" +
	"\fInstallPhase\x12\x1d\n" +
	"\x19INSTALL_PHASE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INSTALL_PHASE_BOOTED_LIVE\x10\x01\x12\"\n" +
	"\x1eINSTALL_PHASE_DISK_PARTITIONED\x10\x02\x12\x1c\n" +
	"\x18INSTALL_PHASE_OS_WRITTEN\x10\x03\x12\x1a\n" +
	"\x16INSTALL_PHASE_REBOOTED\x10\x04\x12\x1a\n" +
	"\x16INSTALL_PHASE_ENROLLED\x10\x05\x12\x17\n" +
	"\x13INSTALL_PHASE_READY\x10\x06\x12\x18\n" +
	"\x14INSTALL_PHASE_FAILED\x10\a2\xa0\x11\n" +
	"\fControlPlane\x12]\n" +
	"\fRegisterNode\x12%.kcore.controller.RegisterNodeRequest\x1a&.kcore.controller.RegisterNodeResponse\x12T\n" +
	"\tHeartbeat\x12\".kcore.controller.HeartbeatRequest\x1a#.kcore.controller.HeartbeatResponse\x12Z\n" +
	"\vSyncVmState\x12$.kcore.controller.SyncVmStateRequest\x1a%.kcore.controller.SyncVmStateResponse\x12Q\n" +
	"\bCreateVm\x12!.kcore.controller.CreateVmRequest\x1a\".kcore.controller.CreateVmResponse\x12Q\n" +
	"\bDeleteVm\x12!.kcore.controller.DeleteVmRequest\x1a\".kcore.controller.DeleteVmResponse\x12N\n" +
	"\aStartVm\x12 .kcore.controller.StartVmRequest\x1a!.kcore.controller.StartVmResponse\x12K\n" +
	"\x06StopVm\x12\x1f.kcore.controller.StopVmRequest\x1a .kcore.controller.StopVmResponse\x12H\n" +
	"\x05GetVm\x12\x1e.kcore.controller.GetVmRequest\x1a\x1f.kcore.controller.GetVmResponse\x12N\n" +
	"\aListVms\x12 .kcore.controller.ListVmsRequest\x1a!.kcore.controller.ListVmsResponse\x12T\n" +
	"\tListNodes\x12\".kcore.controller.ListNodesRequest\x1a#.kcore.controller.ListNodesResponse\x12N\n" +
	"\aGetNode\x12 .kcore.controller.GetNodeRequest\x1a!.kcore.controller.GetNodeResponse\x12m\n" +
	"\x18ApplyControllerNixConfig\x12'.kcore.controller.ApplyNixConfigRequest\x1a(.kcore.controller.ApplyNixConfigResponse\x12m\n" +
	"\x12ApplyNodeNixConfig\x12-.kcore.controlplane.ApplyNodeNixConfigRequest\x1a(.kcore.controller.ApplyNixConfigResponse\x12|\n" +
	"\x15CreateEnrollmentToken\x120.kcore.controlplane.CreateEnrollmentTokenRequest\x1a1.kcore.controlplane.CreateEnrollmentTokenResponse\x12|\n" +
	"\x15RevokeEnrollmentToken\x120.kcore.controlplane.RevokeEnrollmentTokenRequest\x1a1.kcore.controlplane.RevokeEnrollmentTokenResponse\x12y\n" +
	"\x14ListEnrollmentTokens\x12/.kcore.controlplane.ListEnrollmentTokensRequest\x1a0.kcore.controlplane.ListEnrollmentTokensResponse\x12s\n" +
	"\x12GetBootstrapConfig\x12-.kcore.controlplane.GetBootstrapConfigRequest\x1a..kcore.controlplane.GetBootstrapConfigResponse\x12[\n" +
	"\n" +
	"EnrollNode\x12%.kcore.controlplane.EnrollNodeRequest\x1a&.kcore.controlplane.EnrollNodeResponse\x12|\n" +
	"\x15RotateNodeCertificate\x120.kcore.controlplane.RotateNodeCertificateRequest\x1a1.kcore.controlplane.RotateNodeCertificateResponse\x12v\n" +
	"\x13ReportInstallStatus\x12..kcore.controlplane.ReportInstallStatusRequest\x1a/.kcore.controlplane.ReportInstallStatusResponse\x12m\n" +
	"\x10GetInstallStatus\x12+.kcore.controlplane.GetInstallStatusRequest\x1a,.kcore.controlplane.GetInstallStatusResponse\x12p\n" +
	"\x11ListInstallStatus\x12,.kcore.controlplane.ListInstallStatusRequest\x1a-.kcore.controlplane.ListInstallStatusResponseB)Z'github.com/kcore/kcore/api/controlplaneb\x06proto3"

var (
	file_proto_controlplane_proto_rawDescOnce sync.Once
	file_proto_controlplane_proto_rawDescData []byte
)

func file_proto_controlplane_proto_rawDescGZIP() []byte {
	file_proto_controlplane_proto_rawDescOnce.Do(func() {
		file_proto_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_controlplane_proto_rawDesc), len(file_proto_controlplane_proto_rawDesc)))
	})
	return file_proto_controlplane_proto_rawDescData
}

var file_proto_controlplane_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_controlplane_proto_goTypes = []any{
	(EnrollmentTokenScope)(0),                 // 0: kcore.controlplane.EnrollmentTokenScope
	(InstallPhase)(0),                         // 1: kcore.controlplane.InstallPhase
	(*ApplyNodeNixConfigRequest)(nil),         // 2: kcore.controlplane.ApplyNodeNixConfigRequest
	(*CreateEnrollmentTokenRequest)(nil),      // 3: kcore.controlplane.CreateEnrollmentTokenRequest
	(*CreateEnrollmentTokenResponse)(nil),     // 4: kcore.controlplane.CreateEnrollmentTokenResponse
	(*RevokeEnrollmentTokenRequest)(nil),      // 5: kcore.controlplane.RevokeEnrollmentTokenRequest
	(*RevokeEnrollmentTokenResponse)(nil),     // 6: kcore.controlplane.RevokeEnrollmentTokenResponse
	(*EnrollmentTokenInfo)(nil),               // 7: kcore.controlplane.EnrollmentTokenInfo
	(*ListEnrollmentTokensRequest)(nil),       // 8: kcore.controlplane.ListEnrollmentTokensRequest
	(*ListEnrollmentTokensResponse)(nil),      // 9: kcore.controlplane.ListEnrollmentTokensResponse
	(*BootstrapNetworkDefaults)(nil),          // 10: kcore.controlplane.BootstrapNetworkDefaults
	(*BootstrapStorageDefaults)(nil),          // 11: kcore.controlplane.BootstrapStorageDefaults
	(*GetBootstrapConfigRequest)(nil),         // 12: kcore.controlplane.GetBootstrapConfigRequest
	(*GetBootstrapConfigResponse)(nil),        // 13: kcore.controlplane.GetBootstrapConfigResponse
	(*NodeMetadata)(nil),                      // 14: kcore.controlplane.NodeMetadata
	(*EnrollNodeRequest)(nil),                 // 15: kcore.controlplane.EnrollNodeRequest
	(*EnrollNodeResponse)(nil),                // 16: kcore.controlplane.EnrollNodeResponse
	(*RotateNodeCertificateRequest)(nil),      // 17: kcore.controlplane.RotateNodeCertificateRequest
	(*RotateNodeCertificateResponse)(nil),     // 18: kcore.controlplane.RotateNodeCertificateResponse
	(*ReportInstallStatusRequest)(nil),        // 19: kcore.controlplane.ReportInstallStatusRequest
	(*ReportInstallStatusResponse)(nil),       // 20: kcore.controlplane.ReportInstallStatusResponse
	(*GetInstallStatusRequest)(nil),           // 21: kcore.controlplane.GetInstallStatusRequest
	(*InstallStatus)(nil),                     // 22: kcore.controlplane.InstallStatus
	(*GetInstallStatusResponse)(nil),          // 23: kcore.controlplane.GetInstallStatusResponse
	(*ListInstallStatusRequest)(nil),          // 24: kcore.controlplane.ListInstallStatusRequest
	(*ListInstallStatusResponse)(nil),         // 25: kcore.controlplane.ListInstallStatusResponse
	nil,                                       // 26: kcore.controlplane.BootstrapNetworkDefaults.NetworkMapEntry
	nil,                                       // 27: kcore.controlplane.BootstrapStorageDefaults.DriverParametersEntry
	(*controller.ApplyNixConfigRequest)(nil),  // 28: kcore.controller.ApplyNixConfigRequest
	(*timestamppb.Timestamp)(nil),             // 29: google.protobuf.Timestamp
	(*controller.RegisterNodeRequest)(nil),    // 30: kcore.controller.RegisterNodeRequest
	(*controller.HeartbeatRequest)(nil),       // 31: kcore.controller.HeartbeatRequest
	(*controller.SyncVmStateRequest)(nil),     // 32: kcore.controller.SyncVmStateRequest
	(*controller.CreateVmRequest)(nil),        // 33: kcore.controller.CreateVmRequest
	(*controller.DeleteVmRequest)(nil),        // 34: kcore.controller.DeleteVmRequest
	(*controller.StartVmRequest)(nil),         // 35: kcore.controller.StartVmRequest
	(*controller.StopVmRequest)(nil),          // 36: kcore.controller.StopVmRequest
	(*controller.GetVmRequest)(nil),           // 37: kcore.controller.GetVmRequest
	(*controller.ListVmsRequest)(nil),         // 38: kcore.controller.ListVmsRequest
	(*controller.ListNodesRequest)(nil),       // 39: kcore.controller.ListNodesRequest
	(*controller.GetNodeRequest)(nil),         // 40: kcore.controller.GetNodeRequest
	(*controller.RegisterNodeResponse)(nil),   // 41: kcore.controller.RegisterNodeResponse
	(*controller.HeartbeatResponse)(nil),      // 42: kcore.controller.HeartbeatResponse
	(*controller.SyncVmStateResponse)(nil),    // 43: kcore.controller.SyncVmStateResponse
	(*controller.CreateVmResponse)(nil),       // 44: kcore.controller.CreateVmResponse
	(*controller.DeleteVmResponse)(nil),       // 45: kcore.controller.DeleteVmResponse
	(*controller.StartVmResponse)(nil),        // 46: kcore.controller.StartVmResponse
	(*controller.StopVmResponse)(nil),         // 47: kcore.controller.StopVmResponse
	(*controller.GetVmResponse)(nil),          // 48: kcore.controller.GetVmResponse
	(*controller.ListVmsResponse)(nil),        // 49: kcore.controller.ListVmsResponse
	(*controller.ListNodesResponse)(nil),      // 50: kcore.controller.ListNodesResponse
	(*controller.GetNodeResponse)(nil),        // 51: kcore.controller.GetNodeResponse
	(*controller.ApplyNixConfigResponse)(nil), // 52: kcore.controller.ApplyNixConfigResponse
}
var file_proto_controlplane_proto_depIdxs = []int32{
	28, // 0: kcore.controlplane.ApplyNodeNixConfigRequest.config:type_name -> kcore.controller.ApplyNixConfigRequest
	0,  // 1: kcore.controlplane.CreateEnrollmentTokenRequest.scope:type_name -> kcore.controlplane.EnrollmentTokenScope
	29, // 2: kcore.controlplane.CreateEnrollmentTokenRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 3: kcore.controlplane.EnrollmentTokenInfo.scope:type_name -> kcore.controlplane.EnrollmentTokenScope
	29, // 4: kcore.controlplane.EnrollmentTokenInfo.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 5: kcore.controlplane.ListEnrollmentTokensResponse.tokens:type_name -> kcore.controlplane.EnrollmentTokenInfo
	26, // 6: kcore.controlplane.BootstrapNetworkDefaults.network_map:type_name -> kcore.controlplane.BootstrapNetworkDefaults.NetworkMapEntry
	27, // 7: kcore.controlplane.BootstrapStorageDefaults.driver_parameters:type_name -> kcore.controlplane.BootstrapStorageDefaults.DriverParametersEntry
	10, // 8: kcore.controlplane.GetBootstrapConfigResponse.network:type_name -> kcore.controlplane.BootstrapNetworkDefaults
	11, // 9: kcore.controlplane.GetBootstrapConfigResponse.storage:type_name -> kcore.controlplane.BootstrapStorageDefaults
	14, // 10: kcore.controlplane.EnrollNodeRequest.metadata:type_name -> kcore.controlplane.NodeMetadata
	29, // 11: kcore.controlplane.EnrollNodeResponse.cert_expires_at:type_name -> google.protobuf.Timestamp
	29, // 12: kcore.controlplane.RotateNodeCertificateResponse.cert_expires_at:type_name -> google.protobuf.Timestamp
	1,  // 13: kcore.controlplane.ReportInstallStatusRequest.phase:type_name -> kcore.controlplane.InstallPhase
	29, // 14: kcore.controlplane.ReportInstallStatusRequest.observed_at:type_name -> google.protobuf.Timestamp
	1,  // 15: kcore.controlplane.InstallStatus.phase:type_name -> kcore.controlplane.InstallPhase
	29, // 16: kcore.controlplane.InstallStatus.observed_at:type_name -> google.protobuf.Timestamp
	22, // 17: kcore.controlplane.GetInstallStatusResponse.status:type_name -> kcore.controlplane.InstallStatus
	22, // 18: kcore.controlplane.ListInstallStatusResponse.statuses:type_name -> kcore.controlplane.InstallStatus
	30, // 19: kcore.controlplane.ControlPlane.RegisterNode:input_type -> kcore.controller.RegisterNodeRequest
	31, // 20: kcore.controlplane.ControlPlane.Heartbeat:input_type -> kcore.controller.HeartbeatRequest
	32, // 21: kcore.controlplane.ControlPlane.SyncVmState:input_type -> kcore.controller.SyncVmStateRequest
	33, // 22: kcore.controlplane.ControlPlane.CreateVm:input_type -> kcore.controller.CreateVmRequest
	34, // 23: kcore.controlplane.ControlPlane.DeleteVm:input_type -> kcore.controller.DeleteVmRequest
	35, // 24: kcore.controlplane.ControlPlane.StartVm:input_type -> kcore.controller.StartVmRequest
	36, // 25: kcore.controlplane.ControlPlane.StopVm:input_type -> kcore.controller.StopVmRequest
	37, // 26: kcore.controlplane.ControlPlane.GetVm:input_type -> kcore.controller.GetVmRequest
	38, // 27: kcore.controlplane.ControlPlane.ListVms:input_type -> kcore.controller.ListVmsRequest
	39, // 28: kcore.controlplane.ControlPlane.ListNodes:input_type -> kcore.controller.ListNodesRequest
	40, // 29: kcore.controlplane.ControlPlane.GetNode:input_type -> kcore.controller.GetNodeRequest
	28, // 30: kcore.controlplane.ControlPlane.ApplyControllerNixConfig:input_type -> kcore.controller.ApplyNixConfigRequest
	2,  // 31: kcore.controlplane.ControlPlane.ApplyNodeNixConfig:input_type -> kcore.controlplane.ApplyNodeNixConfigRequest
	3,  // 32: kcore.controlplane.ControlPlane.CreateEnrollmentToken:input_type -> kcore.controlplane.CreateEnrollmentTokenRequest
	5,  // 33: kcore.controlplane.ControlPlane.RevokeEnrollmentToken:input_type -> kcore.controlplane.RevokeEnrollmentTokenRequest
	8,  // 34: kcore.controlplane.ControlPlane.ListEnrollmentTokens:input_type -> kcore.controlplane.ListEnrollmentTokensRequest
	12, // 35: kcore.controlplane.ControlPlane.GetBootstrapConfig:input_type -> kcore.controlplane.GetBootstrapConfigRequest
	15, // 36: kcore.controlplane.ControlPlane.EnrollNode:input_type -> kcore.controlplane.EnrollNodeRequest
	17, // 37: kcore.controlplane.ControlPlane.RotateNodeCertificate:input_type -> kcore.controlplane.RotateNodeCertificateRequest
	19, // 38: kcore.controlplane.ControlPlane.ReportInstallStatus:input_type -> kcore.controlplane.ReportInstallStatusRequest
	21, // 39: kcore.controlplane.ControlPlane.GetInstallStatus:input_type -> kcore.controlplane.GetInstallStatusRequest
	24, // 40: kcore.controlplane.ControlPlane.ListInstallStatus:input_type -> kcore.controlplane.ListInstallStatusRequest
	41, // 41: kcore.controlplane.ControlPlane.RegisterNode:output_type -> kcore.controller.RegisterNodeResponse
	42, // 42: kcore.controlplane.ControlPlane.Heartbeat:output_type -> kcore.controller.HeartbeatResponse
	43, // 43: kcore.controlplane.ControlPlane.SyncVmState:output_type -> kcore.controller.SyncVmStateResponse
	44, // 44: kcore.controlplane.ControlPlane.CreateVm:output_type -> kcore.controller.CreateVmResponse
	45, // 45: kcore.controlplane.ControlPlane.DeleteVm:output_type -> kcore.controller.DeleteVmResponse
	46, // 46: kcore.controlplane.ControlPlane.StartVm:output_type -> kcore.controller.StartVmResponse
	47, // 47: kcore.controlplane.ControlPlane.StopVm:output_type -> kcore.controller.StopVmResponse
	48, // 48: kcore.controlplane.ControlPlane.GetVm:output_type -> kcore.controller.GetVmResponse
	49, // 49: kcore.controlplane.ControlPlane.ListVms:output_type -> kcore.controller.ListVmsResponse
	50, // 50: kcore.controlplane.ControlPlane.ListNodes:output_type -> kcore.controller.ListNodesResponse
	51, // 51: kcore.controlplane.ControlPlane.GetNode:output_type -> kcore.controller.GetNodeResponse
	52, // 52: kcore.controlplane.ControlPlane.ApplyControllerNixConfig:output_type -> kcore.controller.ApplyNixConfigResponse
	52, // 53: kcore.controlplane.ControlPlane.ApplyNodeNixConfig:output_type -> kcore.controller.ApplyNixConfigResponse
	4,  // 54: kcore.controlplane.ControlPlane.CreateEnrollmentToken:output_type -> kcore.controlplane.CreateEnrollmentTokenResponse
	6,  // 55: kcore.controlplane.ControlPlane.RevokeEnrollmentToken:output_type -> kcore.controlplane.RevokeEnrollmentTokenResponse
	9,  // 56: kcore.controlplane.ControlPlane.ListEnrollmentTokens:output_type -> kcore.controlplane.ListEnrollmentTokensResponse
	13, // 57: kcore.controlplane.ControlPlane.GetBootstrapConfig:output_type -> kcore.controlplane.GetBootstrapConfigResponse
	16, // 58: kcore.controlplane.ControlPlane.EnrollNode:output_type -> kcore.controlplane.EnrollNodeResponse
	18, // 59: kcore.controlplane.ControlPlane.RotateNodeCertificate:output_type -> kcore.controlplane.RotateNodeCertificateResponse
	20, // 60: kcore.controlplane.ControlPlane.ReportInstallStatus:output_type -> kcore.controlplane.ReportInstallStatusResponse
	23, // 61: kcore.controlplane.ControlPlane.GetInstallStatus:output_type -> kcore.controlplane.GetInstallStatusResponse
	25, // 62: kcore.controlplane.ControlPlane.ListInstallStatus:output_type -> kcore.controlplane.ListInstallStatusResponse
	41, // [41:63] is the sub-list for method output_type
	19, // [19:41] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_controlplane_proto_init() }
func file_proto_controlplane_proto_init() {
	if File_proto_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_controlplane_proto_rawDesc), len(file_proto_controlplane_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_controlplane_proto_goTypes,
		DependencyIndexes: file_proto_controlplane_proto_depIdxs,
		EnumInfos:         file_proto_controlplane_proto_enumTypes,
		MessageInfos:      file_proto_controlplane_proto_msgTypes,
	}.Build()
	File_proto_controlplane_proto = out.File
	file_proto_controlplane_proto_goTypes = nil
	file_proto_controlplane_proto_depIdxs = nil
}
