// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/controlplane.proto

package controlplane

import (
	context "context"
	controller "github.com/kcore/kcore/api/controller"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_RegisterNode_FullMethodName             = "/kcore.controlplane.ControlPlane/RegisterNode"
	ControlPlane_Heartbeat_FullMethodName                = "/kcore.controlplane.ControlPlane/Heartbeat"
	ControlPlane_SyncVmState_FullMethodName              = "/kcore.controlplane.ControlPlane/SyncVmState"
	ControlPlane_CreateVm_FullMethodName                 = "/kcore.controlplane.ControlPlane/CreateVm"
	ControlPlane_DeleteVm_FullMethodName                 = "/kcore.controlplane.ControlPlane/DeleteVm"
	ControlPlane_StartVm_FullMethodName                  = "/kcore.controlplane.ControlPlane/StartVm"
	ControlPlane_StopVm_FullMethodName                   = "/kcore.controlplane.ControlPlane/StopVm"
	ControlPlane_GetVm_FullMethodName                    = "/kcore.controlplane.ControlPlane/GetVm"
	ControlPlane_ListVms_FullMethodName                  = "/kcore.controlplane.ControlPlane/ListVms"
	ControlPlane_ListNodes_FullMethodName                = "/kcore.controlplane.ControlPlane/ListNodes"
	ControlPlane_GetNode_FullMethodName                  = "/kcore.controlplane.ControlPlane/GetNode"
	ControlPlane_ApplyControllerNixConfig_FullMethodName = "/kcore.controlplane.ControlPlane/ApplyControllerNixConfig"
	ControlPlane_ApplyNodeNixConfig_FullMethodName       = "/kcore.controlplane.ControlPlane/ApplyNodeNixConfig"
	ControlPlane_CreateEnrollmentToken_FullMethodName    = "/kcore.controlplane.ControlPlane/CreateEnrollmentToken"
	ControlPlane_RevokeEnrollmentToken_FullMethodName    = "/kcore.controlplane.ControlPlane/RevokeEnrollmentToken"
	ControlPlane_ListEnrollmentTokens_FullMethodName     = "/kcore.controlplane.ControlPlane/ListEnrollmentTokens"
	ControlPlane_GetBootstrapConfig_FullMethodName       = "/kcore.controlplane.ControlPlane/GetBootstrapConfig"
	ControlPlane_EnrollNode_FullMethodName               = "/kcore.controlplane.ControlPlane/EnrollNode"
	ControlPlane_RotateNodeCertificate_FullMethodName    = "/kcore.controlplane.ControlPlane/RotateNodeCertificate"
	ControlPlane_ReportInstallStatus_FullMethodName      = "/kcore.controlplane.ControlPlane/ReportInstallStatus"
	ControlPlane_GetInstallStatus_FullMethodName         = "/kcore.controlplane.ControlPlane/GetInstallStatus"
	ControlPlane_ListInstallStatus_FullMethodName        = "/kcore.controlplane.ControlPlane/ListInstallStatus"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Unified control-plane API: orchestration, admin operations, and day-0 automation.
type ControlPlaneClient interface {
	// Existing orchestration + node lifecycle
	RegisterNode(ctx context.Context, in *controller.RegisterNodeRequest, opts ...grpc.CallOption) (*controller.RegisterNodeResponse, error)
	Heartbeat(ctx context.Context, in *controller.HeartbeatRequest, opts ...grpc.CallOption) (*controller.HeartbeatResponse, error)
	SyncVmState(ctx context.Context, in *controller.SyncVmStateRequest, opts ...grpc.CallOption) (*controller.SyncVmStateResponse, error)
	CreateVm(ctx context.Context, in *controller.CreateVmRequest, opts ...grpc.CallOption) (*controller.CreateVmResponse, error)
	DeleteVm(ctx context.Context, in *controller.DeleteVmRequest, opts ...grpc.CallOption) (*controller.DeleteVmResponse, error)
	StartVm(ctx context.Context, in *controller.StartVmRequest, opts ...grpc.CallOption) (*controller.StartVmResponse, error)
	StopVm(ctx context.Context, in *controller.StopVmRequest, opts ...grpc.CallOption) (*controller.StopVmResponse, error)
	GetVm(ctx context.Context, in *controller.GetVmRequest, opts ...grpc.CallOption) (*controller.GetVmResponse, error)
	ListVms(ctx context.Context, in *controller.ListVmsRequest, opts ...grpc.CallOption) (*controller.ListVmsResponse, error)
	ListNodes(ctx context.Context, in *controller.ListNodesRequest, opts ...grpc.CallOption) (*controller.ListNodesResponse, error)
	GetNode(ctx context.Context, in *controller.GetNodeRequest, opts ...grpc.CallOption) (*controller.GetNodeResponse, error)
	// Existing controller admin operation (kept, but unified under this service)
	ApplyControllerNixConfig(ctx context.Context, in *controller.ApplyNixConfigRequest, opts ...grpc.CallOption) (*controller.ApplyNixConfigResponse, error)
	// Node-targeted admin operation (new)
	ApplyNodeNixConfig(ctx context.Context, in *ApplyNodeNixConfigRequest, opts ...grpc.CallOption) (*controller.ApplyNixConfigResponse, error)
	// Enrollment token management
	CreateEnrollmentToken(ctx context.Context, in *CreateEnrollmentTokenRequest, opts ...grpc.CallOption) (*CreateEnrollmentTokenResponse, error)
	RevokeEnrollmentToken(ctx context.Context, in *RevokeEnrollmentTokenRequest, opts ...grpc.CallOption) (*RevokeEnrollmentTokenResponse, error)
	ListEnrollmentTokens(ctx context.Context, in *ListEnrollmentTokensRequest, opts ...grpc.CallOption) (*ListEnrollmentTokensResponse, error)
	// Day-0 bootstrap and enrollment
	GetBootstrapConfig(ctx context.Context, in *GetBootstrapConfigRequest, opts ...grpc.CallOption) (*GetBootstrapConfigResponse, error)
	EnrollNode(ctx context.Context, in *EnrollNodeRequest, opts ...grpc.CallOption) (*EnrollNodeResponse, error)
	RotateNodeCertificate(ctx context.Context, in *RotateNodeCertificateRequest, opts ...grpc.CallOption) (*RotateNodeCertificateResponse, error)
	// Install progress tracking
	ReportInstallStatus(ctx context.Context, in *ReportInstallStatusRequest, opts ...grpc.CallOption) (*ReportInstallStatusResponse, error)
	GetInstallStatus(ctx context.Context, in *GetInstallStatusRequest, opts ...grpc.CallOption) (*GetInstallStatusResponse, error)
	ListInstallStatus(ctx context.Context, in *ListInstallStatusRequest, opts ...grpc.CallOption) (*ListInstallStatusResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) RegisterNode(ctx context.Context, in *controller.RegisterNodeRequest, opts ...grpc.CallOption) (*controller.RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.RegisterNodeResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, in *controller.HeartbeatRequest, opts ...grpc.CallOption) (*controller.HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) SyncVmState(ctx context.Context, in *controller.SyncVmStateRequest, opts ...grpc.CallOption) (*controller.SyncVmStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.SyncVmStateResponse)
	err := c.cc.Invoke(ctx, ControlPlane_SyncVmState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) CreateVm(ctx context.Context, in *controller.CreateVmRequest, opts ...grpc.CallOption) (*controller.CreateVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.CreateVmResponse)
	err := c.cc.Invoke(ctx, ControlPlane_CreateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) DeleteVm(ctx context.Context, in *controller.DeleteVmRequest, opts ...grpc.CallOption) (*controller.DeleteVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.DeleteVmResponse)
	err := c.cc.Invoke(ctx, ControlPlane_DeleteVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) StartVm(ctx context.Context, in *controller.StartVmRequest, opts ...grpc.CallOption) (*controller.StartVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.StartVmResponse)
	err := c.cc.Invoke(ctx, ControlPlane_StartVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) StopVm(ctx context.Context, in *controller.StopVmRequest, opts ...grpc.CallOption) (*controller.StopVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.StopVmResponse)
	err := c.cc.Invoke(ctx, ControlPlane_StopVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetVm(ctx context.Context, in *controller.GetVmRequest, opts ...grpc.CallOption) (*controller.GetVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.GetVmResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListVms(ctx context.Context, in *controller.ListVmsRequest, opts ...grpc.CallOption) (*controller.ListVmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.ListVmsResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListVms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListNodes(ctx context.Context, in *controller.ListNodesRequest, opts ...grpc.CallOption) (*controller.ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.ListNodesResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetNode(ctx context.Context, in *controller.GetNodeRequest, opts ...grpc.CallOption) (*controller.GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.GetNodeResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ApplyControllerNixConfig(ctx context.Context, in *controller.ApplyNixConfigRequest, opts ...grpc.CallOption) (*controller.ApplyNixConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.ApplyNixConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ApplyControllerNixConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ApplyNodeNixConfig(ctx context.Context, in *ApplyNodeNixConfigRequest, opts ...grpc.CallOption) (*controller.ApplyNixConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.ApplyNixConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ApplyNodeNixConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) CreateEnrollmentToken(ctx context.Context, in *CreateEnrollmentTokenRequest, opts ...grpc.CallOption) (*CreateEnrollmentTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnrollmentTokenResponse)
	err := c.cc.Invoke(ctx, ControlPlane_CreateEnrollmentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RevokeEnrollmentToken(ctx context.Context, in *RevokeEnrollmentTokenRequest, opts ...grpc.CallOption) (*RevokeEnrollmentTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeEnrollmentTokenResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RevokeEnrollmentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListEnrollmentTokens(ctx context.Context, in *ListEnrollmentTokensRequest, opts ...grpc.CallOption) (*ListEnrollmentTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrollmentTokensResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListEnrollmentTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetBootstrapConfig(ctx context.Context, in *GetBootstrapConfigRequest, opts ...grpc.CallOption) (*GetBootstrapConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBootstrapConfigResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetBootstrapConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) EnrollNode(ctx context.Context, in *EnrollNodeRequest, opts ...grpc.CallOption) (*EnrollNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollNodeResponse)
	err := c.cc.Invoke(ctx, ControlPlane_EnrollNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) RotateNodeCertificate(ctx context.Context, in *RotateNodeCertificateRequest, opts ...grpc.CallOption) (*RotateNodeCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateNodeCertificateResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RotateNodeCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ReportInstallStatus(ctx context.Context, in *ReportInstallStatusRequest, opts ...grpc.CallOption) (*ReportInstallStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportInstallStatusResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ReportInstallStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetInstallStatus(ctx context.Context, in *GetInstallStatusRequest, opts ...grpc.CallOption) (*GetInstallStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstallStatusResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetInstallStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListInstallStatus(ctx context.Context, in *ListInstallStatusRequest, opts ...grpc.CallOption) (*ListInstallStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstallStatusResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListInstallStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// Unified control-plane API: orchestration, admin operations, and day-0 automation.
type ControlPlaneServer interface {
	// Existing orchestration + node lifecycle
	RegisterNode(context.Context, *controller.RegisterNodeRequest) (*controller.RegisterNodeResponse, error)
	Heartbeat(context.Context, *controller.HeartbeatRequest) (*controller.HeartbeatResponse, error)
	SyncVmState(context.Context, *controller.SyncVmStateRequest) (*controller.SyncVmStateResponse, error)
	CreateVm(context.Context, *controller.CreateVmRequest) (*controller.CreateVmResponse, error)
	DeleteVm(context.Context, *controller.DeleteVmRequest) (*controller.DeleteVmResponse, error)
	StartVm(context.Context, *controller.StartVmRequest) (*controller.StartVmResponse, error)
	StopVm(context.Context, *controller.StopVmRequest) (*controller.StopVmResponse, error)
	GetVm(context.Context, *controller.GetVmRequest) (*controller.GetVmResponse, error)
	ListVms(context.Context, *controller.ListVmsRequest) (*controller.ListVmsResponse, error)
	ListNodes(context.Context, *controller.ListNodesRequest) (*controller.ListNodesResponse, error)
	GetNode(context.Context, *controller.GetNodeRequest) (*controller.GetNodeResponse, error)
	// Existing controller admin operation (kept, but unified under this service)
	ApplyControllerNixConfig(context.Context, *controller.ApplyNixConfigRequest) (*controller.ApplyNixConfigResponse, error)
	// Node-targeted admin operation (new)
	ApplyNodeNixConfig(context.Context, *ApplyNodeNixConfigRequest) (*controller.ApplyNixConfigResponse, error)
	// Enrollment token management
	CreateEnrollmentToken(context.Context, *CreateEnrollmentTokenRequest) (*CreateEnrollmentTokenResponse, error)
	RevokeEnrollmentToken(context.Context, *RevokeEnrollmentTokenRequest) (*RevokeEnrollmentTokenResponse, error)
	ListEnrollmentTokens(context.Context, *ListEnrollmentTokensRequest) (*ListEnrollmentTokensResponse, error)
	// Day-0 bootstrap and enrollment
	GetBootstrapConfig(context.Context, *GetBootstrapConfigRequest) (*GetBootstrapConfigResponse, error)
	EnrollNode(context.Context, *EnrollNodeRequest) (*EnrollNodeResponse, error)
	RotateNodeCertificate(context.Context, *RotateNodeCertificateRequest) (*RotateNodeCertificateResponse, error)
	// Install progress tracking
	ReportInstallStatus(context.Context, *ReportInstallStatusRequest) (*ReportInstallStatusResponse, error)
	GetInstallStatus(context.Context, *GetInstallStatusRequest) (*GetInstallStatusResponse, error)
	ListInstallStatus(context.Context, *ListInstallStatusRequest) (*ListInstallStatusResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) RegisterNode(context.Context, *controller.RegisterNodeRequest) (*controller.RegisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedControlPlaneServer) Heartbeat(context.Context, *controller.HeartbeatRequest) (*controller.HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) SyncVmState(context.Context, *controller.SyncVmStateRequest) (*controller.SyncVmStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncVmState not implemented")
}
func (UnimplementedControlPlaneServer) CreateVm(context.Context, *controller.CreateVmRequest) (*controller.CreateVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVm not implemented")
}
func (UnimplementedControlPlaneServer) DeleteVm(context.Context, *controller.DeleteVmRequest) (*controller.DeleteVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVm not implemented")
}
func (UnimplementedControlPlaneServer) StartVm(context.Context, *controller.StartVmRequest) (*controller.StartVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVm not implemented")
}
func (UnimplementedControlPlaneServer) StopVm(context.Context, *controller.StopVmRequest) (*controller.StopVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVm not implemented")
}
func (UnimplementedControlPlaneServer) GetVm(context.Context, *controller.GetVmRequest) (*controller.GetVmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVm not implemented")
}
func (UnimplementedControlPlaneServer) ListVms(context.Context, *controller.ListVmsRequest) (*controller.ListVmsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVms not implemented")
}
func (UnimplementedControlPlaneServer) ListNodes(context.Context, *controller.ListNodesRequest) (*controller.ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedControlPlaneServer) GetNode(context.Context, *controller.GetNodeRequest) (*controller.GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedControlPlaneServer) ApplyControllerNixConfig(context.Context, *controller.ApplyNixConfigRequest) (*controller.ApplyNixConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyControllerNixConfig not implemented")
}
func (UnimplementedControlPlaneServer) ApplyNodeNixConfig(context.Context, *ApplyNodeNixConfigRequest) (*controller.ApplyNixConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyNodeNixConfig not implemented")
}
func (UnimplementedControlPlaneServer) CreateEnrollmentToken(context.Context, *CreateEnrollmentTokenRequest) (*CreateEnrollmentTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnrollmentToken not implemented")
}
func (UnimplementedControlPlaneServer) RevokeEnrollmentToken(context.Context, *RevokeEnrollmentTokenRequest) (*RevokeEnrollmentTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeEnrollmentToken not implemented")
}
func (UnimplementedControlPlaneServer) ListEnrollmentTokens(context.Context, *ListEnrollmentTokensRequest) (*ListEnrollmentTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnrollmentTokens not implemented")
}
func (UnimplementedControlPlaneServer) GetBootstrapConfig(context.Context, *GetBootstrapConfigRequest) (*GetBootstrapConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBootstrapConfig not implemented")
}
func (UnimplementedControlPlaneServer) EnrollNode(context.Context, *EnrollNodeRequest) (*EnrollNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrollNode not implemented")
}
func (UnimplementedControlPlaneServer) RotateNodeCertificate(context.Context, *RotateNodeCertificateRequest) (*RotateNodeCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateNodeCertificate not implemented")
}
func (UnimplementedControlPlaneServer) ReportInstallStatus(context.Context, *ReportInstallStatusRequest) (*ReportInstallStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportInstallStatus not implemented")
}
func (UnimplementedControlPlaneServer) GetInstallStatus(context.Context, *GetInstallStatusRequest) (*GetInstallStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstallStatus not implemented")
}
func (UnimplementedControlPlaneServer) ListInstallStatus(context.Context, *ListInstallStatusRequest) (*ListInstallStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstallStatus not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call pancis, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterNode(ctx, req.(*controller.RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Heartbeat(ctx, req.(*controller.HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_SyncVmState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.SyncVmStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).SyncVmState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_SyncVmState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).SyncVmState(ctx, req.(*controller.SyncVmStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_CreateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.CreateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).CreateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_CreateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).CreateVm(ctx, req.(*controller.CreateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_DeleteVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.DeleteVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).DeleteVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_DeleteVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).DeleteVm(ctx, req.(*controller.DeleteVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_StartVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.StartVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).StartVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_StartVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).StartVm(ctx, req.(*controller.StartVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_StopVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.StopVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).StopVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_StopVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).StopVm(ctx, req.(*controller.StopVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.GetVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetVm(ctx, req.(*controller.GetVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListVms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.ListVmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListVms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListVms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListVms(ctx, req.(*controller.ListVmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListNodes(ctx, req.(*controller.ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetNode(ctx, req.(*controller.GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ApplyControllerNixConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.ApplyNixConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ApplyControllerNixConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ApplyControllerNixConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ApplyControllerNixConfig(ctx, req.(*controller.ApplyNixConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ApplyNodeNixConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyNodeNixConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ApplyNodeNixConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ApplyNodeNixConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ApplyNodeNixConfig(ctx, req.(*ApplyNodeNixConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_CreateEnrollmentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnrollmentTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).CreateEnrollmentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_CreateEnrollmentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).CreateEnrollmentToken(ctx, req.(*CreateEnrollmentTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RevokeEnrollmentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeEnrollmentTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RevokeEnrollmentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RevokeEnrollmentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RevokeEnrollmentToken(ctx, req.(*RevokeEnrollmentTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListEnrollmentTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrollmentTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListEnrollmentTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListEnrollmentTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListEnrollmentTokens(ctx, req.(*ListEnrollmentTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetBootstrapConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBootstrapConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetBootstrapConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetBootstrapConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetBootstrapConfig(ctx, req.(*GetBootstrapConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_EnrollNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).EnrollNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_EnrollNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).EnrollNode(ctx, req.(*EnrollNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_RotateNodeCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateNodeCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RotateNodeCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RotateNodeCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RotateNodeCertificate(ctx, req.(*RotateNodeCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ReportInstallStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportInstallStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReportInstallStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReportInstallStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReportInstallStatus(ctx, req.(*ReportInstallStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetInstallStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstallStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetInstallStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetInstallStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetInstallStatus(ctx, req.(*GetInstallStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListInstallStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstallStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListInstallStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListInstallStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListInstallStatus(ctx, req.(*ListInstallStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kcore.controlplane.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _ControlPlane_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlane_Heartbeat_Handler,
		},
		{
			MethodName: "SyncVmState",
			Handler:    _ControlPlane_SyncVmState_Handler,
		},
		{
			MethodName: "CreateVm",
			Handler:    _ControlPlane_CreateVm_Handler,
		},
		{
			MethodName: "DeleteVm",
			Handler:    _ControlPlane_DeleteVm_Handler,
		},
		{
			MethodName: "StartVm",
			Handler:    _ControlPlane_StartVm_Handler,
		},
		{
			MethodName: "StopVm",
			Handler:    _ControlPlane_StopVm_Handler,
		},
		{
			MethodName: "GetVm",
			Handler:    _ControlPlane_GetVm_Handler,
		},
		{
			MethodName: "ListVms",
			Handler:    _ControlPlane_ListVms_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _ControlPlane_ListNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _ControlPlane_GetNode_Handler,
		},
		{
			MethodName: "ApplyControllerNixConfig",
			Handler:    _ControlPlane_ApplyControllerNixConfig_Handler,
		},
		{
			MethodName: "ApplyNodeNixConfig",
			Handler:    _ControlPlane_ApplyNodeNixConfig_Handler,
		},
		{
			MethodName: "CreateEnrollmentToken",
			Handler:    _ControlPlane_CreateEnrollmentToken_Handler,
		},
		{
			MethodName: "RevokeEnrollmentToken",
			Handler:    _ControlPlane_RevokeEnrollmentToken_Handler,
		},
		{
			MethodName: "ListEnrollmentTokens",
			Handler:    _ControlPlane_ListEnrollmentTokens_Handler,
		},
		{
			MethodName: "GetBootstrapConfig",
			Handler:    _ControlPlane_GetBootstrapConfig_Handler,
		},
		{
			MethodName: "EnrollNode",
			Handler:    _ControlPlane_EnrollNode_Handler,
		},
		{
			MethodName: "RotateNodeCertificate",
			Handler:    _ControlPlane_RotateNodeCertificate_Handler,
		},
		{
			MethodName: "ReportInstallStatus",
			Handler:    _ControlPlane_ReportInstallStatus_Handler,
		},
		{
			MethodName: "GetInstallStatus",
			Handler:    _ControlPlane_GetInstallStatus_Handler,
		},
		{
			MethodName: "ListInstallStatus",
			Handler:    _ControlPlane_ListInstallStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/controlplane.proto",
}
