// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: proto/controller.proto

package controller

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Controller_RegisterNode_FullMethodName          = "/kcore.controller.Controller/RegisterNode"
	Controller_Heartbeat_FullMethodName             = "/kcore.controller.Controller/Heartbeat"
	Controller_SyncVmState_FullMethodName           = "/kcore.controller.Controller/SyncVmState"
	Controller_CreateVm_FullMethodName              = "/kcore.controller.Controller/CreateVm"
	Controller_DeleteVm_FullMethodName              = "/kcore.controller.Controller/DeleteVm"
	Controller_StartVm_FullMethodName               = "/kcore.controller.Controller/StartVm"
	Controller_StopVm_FullMethodName                = "/kcore.controller.Controller/StopVm"
	Controller_GetVm_FullMethodName                 = "/kcore.controller.Controller/GetVm"
	Controller_ListVms_FullMethodName               = "/kcore.controller.Controller/ListVms"
	Controller_ListNodes_FullMethodName             = "/kcore.controller.Controller/ListNodes"
	Controller_GetNode_FullMethodName               = "/kcore.controller.Controller/GetNode"
	Controller_ListNodeDisks_FullMethodName         = "/kcore.controller.Controller/ListNodeDisks"
	Controller_ListNetworkInterfaces_FullMethodName = "/kcore.controller.Controller/ListNetworkInterfaces"
	Controller_InstallNode_FullMethodName           = "/kcore.controller.Controller/InstallNode"
	Controller_GetInstallStatus_FullMethodName      = "/kcore.controller.Controller/GetInstallStatus"
	Controller_ConfigureNetwork_FullMethodName      = "/kcore.controller.Controller/ConfigureNetwork"
	Controller_UpdateNixConfig_FullMethodName       = "/kcore.controller.Controller/UpdateNixConfig"
	Controller_RebuildNix_FullMethodName            = "/kcore.controller.Controller/RebuildNix"
	Controller_UpdateSystem_FullMethodName          = "/kcore.controller.Controller/UpdateSystem"
)

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Controller service - orchestrates VMs across nodes
type ControllerClient interface {
	// Node registration and heartbeat
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	SyncVmState(ctx context.Context, in *SyncVmStateRequest, opts ...grpc.CallOption) (*SyncVmStateResponse, error)
	// VM operations (forwarded to nodes)
	CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error)
	DeleteVm(ctx context.Context, in *DeleteVmRequest, opts ...grpc.CallOption) (*DeleteVmResponse, error)
	StartVm(ctx context.Context, in *StartVmRequest, opts ...grpc.CallOption) (*StartVmResponse, error)
	StopVm(ctx context.Context, in *StopVmRequest, opts ...grpc.CallOption) (*StopVmResponse, error)
	GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*GetVmResponse, error)
	ListVms(ctx context.Context, in *ListVmsRequest, opts ...grpc.CallOption) (*ListVmsResponse, error)
	// Node operations
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// Automator: Day-0 hardware discovery
	ListNodeDisks(ctx context.Context, in *ListNodeDisksRequest, opts ...grpc.CallOption) (*ListNodeDisksResponse, error)
	ListNetworkInterfaces(ctx context.Context, in *ListNetworkInterfacesRequest, opts ...grpc.CallOption) (*ListNetworkInterfacesResponse, error)
	// Automator: Day-0 node provisioning
	InstallNode(ctx context.Context, in *InstallNodeRequest, opts ...grpc.CallOption) (*InstallNodeResponse, error)
	GetInstallStatus(ctx context.Context, in *GetInstallStatusRequest, opts ...grpc.CallOption) (*GetInstallStatusResponse, error)
	ConfigureNetwork(ctx context.Context, in *ConfigureNetworkRequest, opts ...grpc.CallOption) (*ConfigureNetworkResponse, error)
	// Automator: Day-N system management
	UpdateNixConfig(ctx context.Context, in *UpdateNixConfigRequest, opts ...grpc.CallOption) (*UpdateNixConfigResponse, error)
	RebuildNix(ctx context.Context, in *RebuildNixRequest, opts ...grpc.CallOption) (*RebuildNixResponse, error)
	UpdateSystem(ctx context.Context, in *UpdateSystemRequest, opts ...grpc.CallOption) (*UpdateSystemResponse, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, Controller_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Controller_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) SyncVmState(ctx context.Context, in *SyncVmStateRequest, opts ...grpc.CallOption) (*SyncVmStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncVmStateResponse)
	err := c.cc.Invoke(ctx, Controller_SyncVmState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*CreateVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVmResponse)
	err := c.cc.Invoke(ctx, Controller_CreateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DeleteVm(ctx context.Context, in *DeleteVmRequest, opts ...grpc.CallOption) (*DeleteVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVmResponse)
	err := c.cc.Invoke(ctx, Controller_DeleteVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) StartVm(ctx context.Context, in *StartVmRequest, opts ...grpc.CallOption) (*StartVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVmResponse)
	err := c.cc.Invoke(ctx, Controller_StartVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) StopVm(ctx context.Context, in *StopVmRequest, opts ...grpc.CallOption) (*StopVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopVmResponse)
	err := c.cc.Invoke(ctx, Controller_StopVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*GetVmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVmResponse)
	err := c.cc.Invoke(ctx, Controller_GetVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListVms(ctx context.Context, in *ListVmsRequest, opts ...grpc.CallOption) (*ListVmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVmsResponse)
	err := c.cc.Invoke(ctx, Controller_ListVms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, Controller_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, Controller_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListNodeDisks(ctx context.Context, in *ListNodeDisksRequest, opts ...grpc.CallOption) (*ListNodeDisksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodeDisksResponse)
	err := c.cc.Invoke(ctx, Controller_ListNodeDisks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListNetworkInterfaces(ctx context.Context, in *ListNetworkInterfacesRequest, opts ...grpc.CallOption) (*ListNetworkInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworkInterfacesResponse)
	err := c.cc.Invoke(ctx, Controller_ListNetworkInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) InstallNode(ctx context.Context, in *InstallNodeRequest, opts ...grpc.CallOption) (*InstallNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallNodeResponse)
	err := c.cc.Invoke(ctx, Controller_InstallNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetInstallStatus(ctx context.Context, in *GetInstallStatusRequest, opts ...grpc.CallOption) (*GetInstallStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstallStatusResponse)
	err := c.cc.Invoke(ctx, Controller_GetInstallStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ConfigureNetwork(ctx context.Context, in *ConfigureNetworkRequest, opts ...grpc.CallOption) (*ConfigureNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureNetworkResponse)
	err := c.cc.Invoke(ctx, Controller_ConfigureNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) UpdateNixConfig(ctx context.Context, in *UpdateNixConfigRequest, opts ...grpc.CallOption) (*UpdateNixConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNixConfigResponse)
	err := c.cc.Invoke(ctx, Controller_UpdateNixConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) RebuildNix(ctx context.Context, in *RebuildNixRequest, opts ...grpc.CallOption) (*RebuildNixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildNixResponse)
	err := c.cc.Invoke(ctx, Controller_RebuildNix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) UpdateSystem(ctx context.Context, in *UpdateSystemRequest, opts ...grpc.CallOption) (*UpdateSystemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSystemResponse)
	err := c.cc.Invoke(ctx, Controller_UpdateSystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility.
//
// Controller service - orchestrates VMs across nodes
type ControllerServer interface {
	// Node registration and heartbeat
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	SyncVmState(context.Context, *SyncVmStateRequest) (*SyncVmStateResponse, error)
	// VM operations (forwarded to nodes)
	CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error)
	DeleteVm(context.Context, *DeleteVmRequest) (*DeleteVmResponse, error)
	StartVm(context.Context, *StartVmRequest) (*StartVmResponse, error)
	StopVm(context.Context, *StopVmRequest) (*StopVmResponse, error)
	GetVm(context.Context, *GetVmRequest) (*GetVmResponse, error)
	ListVms(context.Context, *ListVmsRequest) (*ListVmsResponse, error)
	// Node operations
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// Automator: Day-0 hardware discovery
	ListNodeDisks(context.Context, *ListNodeDisksRequest) (*ListNodeDisksResponse, error)
	ListNetworkInterfaces(context.Context, *ListNetworkInterfacesRequest) (*ListNetworkInterfacesResponse, error)
	// Automator: Day-0 node provisioning
	InstallNode(context.Context, *InstallNodeRequest) (*InstallNodeResponse, error)
	GetInstallStatus(context.Context, *GetInstallStatusRequest) (*GetInstallStatusResponse, error)
	ConfigureNetwork(context.Context, *ConfigureNetworkRequest) (*ConfigureNetworkResponse, error)
	// Automator: Day-N system management
	UpdateNixConfig(context.Context, *UpdateNixConfigRequest) (*UpdateNixConfigResponse, error)
	RebuildNix(context.Context, *RebuildNixRequest) (*RebuildNixResponse, error)
	UpdateSystem(context.Context, *UpdateSystemRequest) (*UpdateSystemResponse, error)
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServer struct{}

func (UnimplementedControllerServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedControllerServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControllerServer) SyncVmState(context.Context, *SyncVmStateRequest) (*SyncVmStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncVmState not implemented")
}
func (UnimplementedControllerServer) CreateVm(context.Context, *CreateVmRequest) (*CreateVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVm not implemented")
}
func (UnimplementedControllerServer) DeleteVm(context.Context, *DeleteVmRequest) (*DeleteVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVm not implemented")
}
func (UnimplementedControllerServer) StartVm(context.Context, *StartVmRequest) (*StartVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVm not implemented")
}
func (UnimplementedControllerServer) StopVm(context.Context, *StopVmRequest) (*StopVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVm not implemented")
}
func (UnimplementedControllerServer) GetVm(context.Context, *GetVmRequest) (*GetVmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVm not implemented")
}
func (UnimplementedControllerServer) ListVms(context.Context, *ListVmsRequest) (*ListVmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVms not implemented")
}
func (UnimplementedControllerServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedControllerServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedControllerServer) ListNodeDisks(context.Context, *ListNodeDisksRequest) (*ListNodeDisksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodeDisks not implemented")
}
func (UnimplementedControllerServer) ListNetworkInterfaces(context.Context, *ListNetworkInterfacesRequest) (*ListNetworkInterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworkInterfaces not implemented")
}
func (UnimplementedControllerServer) InstallNode(context.Context, *InstallNodeRequest) (*InstallNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallNode not implemented")
}
func (UnimplementedControllerServer) GetInstallStatus(context.Context, *GetInstallStatusRequest) (*GetInstallStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstallStatus not implemented")
}
func (UnimplementedControllerServer) ConfigureNetwork(context.Context, *ConfigureNetworkRequest) (*ConfigureNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureNetwork not implemented")
}
func (UnimplementedControllerServer) UpdateNixConfig(context.Context, *UpdateNixConfigRequest) (*UpdateNixConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNixConfig not implemented")
}
func (UnimplementedControllerServer) RebuildNix(context.Context, *RebuildNixRequest) (*RebuildNixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildNix not implemented")
}
func (UnimplementedControllerServer) UpdateSystem(context.Context, *UpdateSystemRequest) (*UpdateSystemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSystem not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}
func (UnimplementedControllerServer) testEmbeddedByValue()                    {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	// If the following call panics, it indicates UnimplementedControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_SyncVmState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncVmStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).SyncVmState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_SyncVmState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).SyncVmState(ctx, req.(*SyncVmStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_CreateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_CreateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateVm(ctx, req.(*CreateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DeleteVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DeleteVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_DeleteVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DeleteVm(ctx, req.(*DeleteVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_StartVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).StartVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_StartVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).StartVm(ctx, req.(*StartVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_StopVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).StopVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_StopVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).StopVm(ctx, req.(*StopVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetVm(ctx, req.(*GetVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListVms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListVms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListVms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListVms(ctx, req.(*ListVmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListNodeDisks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeDisksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListNodeDisks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListNodeDisks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListNodeDisks(ctx, req.(*ListNodeDisksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListNetworkInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworkInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ListNetworkInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ListNetworkInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ListNetworkInterfaces(ctx, req.(*ListNetworkInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_InstallNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).InstallNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_InstallNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).InstallNode(ctx, req.(*InstallNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetInstallStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstallStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetInstallStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetInstallStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetInstallStatus(ctx, req.(*GetInstallStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ConfigureNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ConfigureNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ConfigureNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ConfigureNetwork(ctx, req.(*ConfigureNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_UpdateNixConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNixConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UpdateNixConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_UpdateNixConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UpdateNixConfig(ctx, req.(*UpdateNixConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_RebuildNix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildNixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).RebuildNix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_RebuildNix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).RebuildNix(ctx, req.(*RebuildNixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_UpdateSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UpdateSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_UpdateSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UpdateSystem(ctx, req.(*UpdateSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kcore.controller.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _Controller_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Controller_Heartbeat_Handler,
		},
		{
			MethodName: "SyncVmState",
			Handler:    _Controller_SyncVmState_Handler,
		},
		{
			MethodName: "CreateVm",
			Handler:    _Controller_CreateVm_Handler,
		},
		{
			MethodName: "DeleteVm",
			Handler:    _Controller_DeleteVm_Handler,
		},
		{
			MethodName: "StartVm",
			Handler:    _Controller_StartVm_Handler,
		},
		{
			MethodName: "StopVm",
			Handler:    _Controller_StopVm_Handler,
		},
		{
			MethodName: "GetVm",
			Handler:    _Controller_GetVm_Handler,
		},
		{
			MethodName: "ListVms",
			Handler:    _Controller_ListVms_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Controller_ListNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Controller_GetNode_Handler,
		},
		{
			MethodName: "ListNodeDisks",
			Handler:    _Controller_ListNodeDisks_Handler,
		},
		{
			MethodName: "ListNetworkInterfaces",
			Handler:    _Controller_ListNetworkInterfaces_Handler,
		},
		{
			MethodName: "InstallNode",
			Handler:    _Controller_InstallNode_Handler,
		},
		{
			MethodName: "GetInstallStatus",
			Handler:    _Controller_GetInstallStatus_Handler,
		},
		{
			MethodName: "ConfigureNetwork",
			Handler:    _Controller_ConfigureNetwork_Handler,
		},
		{
			MethodName: "UpdateNixConfig",
			Handler:    _Controller_UpdateNixConfig_Handler,
		},
		{
			MethodName: "RebuildNix",
			Handler:    _Controller_RebuildNix_Handler,
		},
		{
			MethodName: "UpdateSystem",
			Handler:    _Controller_UpdateSystem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/controller.proto",
}

const (
	ControllerAdmin_ApplyNixConfig_FullMethodName = "/kcore.controller.ControllerAdmin/ApplyNixConfig"
)

// ControllerAdminClient is the client API for ControllerAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControllerAdmin service provides controller-level management operations.
// For now this is intentionally unauthenticated and simple, for development use.
type ControllerAdminClient interface {
	// ApplyNixConfig replaces the controller's /etc/nixos/configuration.nix with
	// the provided content and (optionally) triggers a nixos-rebuild.
	ApplyNixConfig(ctx context.Context, in *ApplyNixConfigRequest, opts ...grpc.CallOption) (*ApplyNixConfigResponse, error)
}

type controllerAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerAdminClient(cc grpc.ClientConnInterface) ControllerAdminClient {
	return &controllerAdminClient{cc}
}

func (c *controllerAdminClient) ApplyNixConfig(ctx context.Context, in *ApplyNixConfigRequest, opts ...grpc.CallOption) (*ApplyNixConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyNixConfigResponse)
	err := c.cc.Invoke(ctx, ControllerAdmin_ApplyNixConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerAdminServer is the server API for ControllerAdmin service.
// All implementations must embed UnimplementedControllerAdminServer
// for forward compatibility.
//
// ControllerAdmin service provides controller-level management operations.
// For now this is intentionally unauthenticated and simple, for development use.
type ControllerAdminServer interface {
	// ApplyNixConfig replaces the controller's /etc/nixos/configuration.nix with
	// the provided content and (optionally) triggers a nixos-rebuild.
	ApplyNixConfig(context.Context, *ApplyNixConfigRequest) (*ApplyNixConfigResponse, error)
	mustEmbedUnimplementedControllerAdminServer()
}

// UnimplementedControllerAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerAdminServer struct{}

func (UnimplementedControllerAdminServer) ApplyNixConfig(context.Context, *ApplyNixConfigRequest) (*ApplyNixConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyNixConfig not implemented")
}
func (UnimplementedControllerAdminServer) mustEmbedUnimplementedControllerAdminServer() {}
func (UnimplementedControllerAdminServer) testEmbeddedByValue()                         {}

// UnsafeControllerAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerAdminServer will
// result in compilation errors.
type UnsafeControllerAdminServer interface {
	mustEmbedUnimplementedControllerAdminServer()
}

func RegisterControllerAdminServer(s grpc.ServiceRegistrar, srv ControllerAdminServer) {
	// If the following call panics, it indicates UnimplementedControllerAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerAdmin_ServiceDesc, srv)
}

func _ControllerAdmin_ApplyNixConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyNixConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerAdminServer).ApplyNixConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerAdmin_ApplyNixConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerAdminServer).ApplyNixConfig(ctx, req.(*ApplyNixConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerAdmin_ServiceDesc is the grpc.ServiceDesc for ControllerAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kcore.controller.ControllerAdmin",
	HandlerType: (*ControllerAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyNixConfig",
			Handler:    _ControllerAdmin_ApplyNixConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/controller.proto",
}
