nodeId: kvm-node-01
controllerAddr: "192.168.40.146:9090"

tls:
  caFile: "/etc/kcore/certs/ca.crt"
  certFile: "/etc/kcore/certs/node.crt"
  keyFile: "/etc/kcore/certs/node.key"

networks:
  default: virbr0

storage:
  drivers:
    local-dir:
      type: local-dir
      parameters:
        path: /var/lib/kcore/disks

