nodeId: kvm-node-01
controllerAddr: "192.168.40.146:9090"

tls:
  caFile: "/etc/kcode/certs/ca.crt"
  certFile: "/etc/kcode/certs/node.crt"
  keyFile: "/etc/kcode/certs/node.key"

networks:
  default: br0
  storage: br1

storage:
  drivers:
    local-dir:
      type: local-dir
      parameters:
        path: /var/lib/kcode/disks

