// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/controller.proto

package controller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmState int32

const (
	VmState_VM_STATE_UNKNOWN VmState = 0
	VmState_VM_STATE_STOPPED VmState = 1
	VmState_VM_STATE_RUNNING VmState = 2
	VmState_VM_STATE_PAUSED  VmState = 3
	VmState_VM_STATE_ERROR   VmState = 4
)

// Enum value maps for VmState.
var (
	VmState_name = map[int32]string{
		0: "VM_STATE_UNKNOWN",
		1: "VM_STATE_STOPPED",
		2: "VM_STATE_RUNNING",
		3: "VM_STATE_PAUSED",
		4: "VM_STATE_ERROR",
	}
	VmState_value = map[string]int32{
		"VM_STATE_UNKNOWN": 0,
		"VM_STATE_STOPPED": 1,
		"VM_STATE_RUNNING": 2,
		"VM_STATE_PAUSED":  3,
		"VM_STATE_ERROR":   4,
	}
)

func (x VmState) Enum() *VmState {
	p := new(VmState)
	*p = x
	return p
}

func (x VmState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_controller_proto_enumTypes[0].Descriptor()
}

func (VmState) Type() protoreflect.EnumType {
	return &file_proto_controller_proto_enumTypes[0]
}

func (x VmState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmState.Descriptor instead.
func (VmState) EnumDescriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{0}
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // gRPC endpoint address
	Capacity      *NodeCapacity          `protobuf:"bytes,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Labels        []string               `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"` // e.g., "dc=dc-a", "rack=rack-1"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterNodeRequest) GetCapacity() *NodeCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *RegisterNodeRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Usage         *NodeUsage             `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetUsage() *NodeUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SyncVmStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Vms           []*VmInfo              `protobuf:"bytes,2,rep,name=vms,proto3" json:"vms,omitempty"` // Complete list of VMs currently on this node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncVmStateRequest) Reset() {
	*x = SyncVmStateRequest{}
	mi := &file_proto_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncVmStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncVmStateRequest) ProtoMessage() {}

func (x *SyncVmStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncVmStateRequest.ProtoReflect.Descriptor instead.
func (*SyncVmStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{4}
}

func (x *SyncVmStateRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncVmStateRequest) GetVms() []*VmInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

type SyncVmStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncVmStateResponse) Reset() {
	*x = SyncVmStateResponse{}
	mi := &file_proto_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncVmStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncVmStateResponse) ProtoMessage() {}

func (x *SyncVmStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncVmStateResponse.ProtoReflect.Descriptor instead.
func (*SyncVmStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{5}
}

func (x *SyncVmStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type NodeCapacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapacity) Reset() {
	*x = NodeCapacity{}
	mi := &file_proto_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapacity) ProtoMessage() {}

func (x *NodeCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapacity.ProtoReflect.Descriptor instead.
func (*NodeCapacity) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{6}
}

func (x *NodeCapacity) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeCapacity) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type NodeUsage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuCoresUsed    int32                  `protobuf:"varint,1,opt,name=cpu_cores_used,json=cpuCoresUsed,proto3" json:"cpu_cores_used,omitempty"`
	MemoryBytesUsed int64                  `protobuf:"varint,2,opt,name=memory_bytes_used,json=memoryBytesUsed,proto3" json:"memory_bytes_used,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeUsage) Reset() {
	*x = NodeUsage{}
	mi := &file_proto_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUsage) ProtoMessage() {}

func (x *NodeUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUsage.ProtoReflect.Descriptor instead.
func (*NodeUsage) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{7}
}

func (x *NodeUsage) GetCpuCoresUsed() int32 {
	if x != nil {
		return x.CpuCoresUsed
	}
	return 0
}

func (x *NodeUsage) GetMemoryBytesUsed() int64 {
	if x != nil {
		return x.MemoryBytesUsed
	}
	return 0
}

type CreateVmRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetNode        string                 `protobuf:"bytes,1,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"` // Node address (e.g., "192.168.1.10:9091") - optional, controller picks if empty
	Spec              *VmSpec                `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	ImageUri          string                 `protobuf:"bytes,3,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`                                // HTTP/HTTPS URI to download image
	CloudInitUserData string                 `protobuf:"bytes,4,opt,name=cloud_init_user_data,json=cloudInitUserData,proto3" json:"cloud_init_user_data,omitempty"` // Custom cloud-init #cloud-config YAML
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_proto_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVmRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *CreateVmRequest) GetSpec() *VmSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CreateVmRequest) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *CreateVmRequest) GetCloudInitUserData() string {
	if x != nil {
		return x.CloudInitUserData
	}
	return ""
}

type CreateVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Which node created it
	State         VmState                `protobuf:"varint,3,opt,name=state,proto3,enum=kcore.controller.VmState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmResponse) Reset() {
	*x = CreateVmResponse{}
	mi := &file_proto_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse) ProtoMessage() {}

func (x *CreateVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse.ProtoReflect.Descriptor instead.
func (*CreateVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVmResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVmResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateVmResponse) GetState() VmState {
	if x != nil {
		return x.State
	}
	return VmState_VM_STATE_UNKNOWN
}

type DeleteVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	TargetNode    string                 `protobuf:"bytes,2,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"` // Optional - controller finds it if empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVmRequest) Reset() {
	*x = DeleteVmRequest{}
	mi := &file_proto_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmRequest) ProtoMessage() {}

func (x *DeleteVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmRequest.ProtoReflect.Descriptor instead.
func (*DeleteVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *DeleteVmRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

type DeleteVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVmResponse) Reset() {
	*x = DeleteVmResponse{}
	mi := &file_proto_controller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmResponse) ProtoMessage() {}

func (x *DeleteVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmResponse.ProtoReflect.Descriptor instead.
func (*DeleteVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteVmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	TargetNode    string                 `protobuf:"bytes,2,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmRequest) Reset() {
	*x = StartVmRequest{}
	mi := &file_proto_controller_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmRequest) ProtoMessage() {}

func (x *StartVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmRequest.ProtoReflect.Descriptor instead.
func (*StartVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{12}
}

func (x *StartVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StartVmRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

type StartVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         VmState                `protobuf:"varint,1,opt,name=state,proto3,enum=kcore.controller.VmState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmResponse) Reset() {
	*x = StartVmResponse{}
	mi := &file_proto_controller_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmResponse) ProtoMessage() {}

func (x *StartVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmResponse.ProtoReflect.Descriptor instead.
func (*StartVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{13}
}

func (x *StartVmResponse) GetState() VmState {
	if x != nil {
		return x.State
	}
	return VmState_VM_STATE_UNKNOWN
}

type StopVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	TargetNode    string                 `protobuf:"bytes,3,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmRequest) Reset() {
	*x = StopVmRequest{}
	mi := &file_proto_controller_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmRequest) ProtoMessage() {}

func (x *StopVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmRequest.ProtoReflect.Descriptor instead.
func (*StopVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{14}
}

func (x *StopVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StopVmRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *StopVmRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

type StopVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         VmState                `protobuf:"varint,1,opt,name=state,proto3,enum=kcore.controller.VmState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmResponse) Reset() {
	*x = StopVmResponse{}
	mi := &file_proto_controller_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmResponse) ProtoMessage() {}

func (x *StopVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmResponse.ProtoReflect.Descriptor instead.
func (*StopVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{15}
}

func (x *StopVmResponse) GetState() VmState {
	if x != nil {
		return x.State
	}
	return VmState_VM_STATE_UNKNOWN
}

type GetVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	TargetNode    string                 `protobuf:"bytes,2,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmRequest) Reset() {
	*x = GetVmRequest{}
	mi := &file_proto_controller_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmRequest) ProtoMessage() {}

func (x *GetVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmRequest.ProtoReflect.Descriptor instead.
func (*GetVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{16}
}

func (x *GetVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *GetVmRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

type GetVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *VmSpec                `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *VmStatus              `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Which node it's on
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmResponse) Reset() {
	*x = GetVmResponse{}
	mi := &file_proto_controller_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmResponse) ProtoMessage() {}

func (x *GetVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmResponse.ProtoReflect.Descriptor instead.
func (*GetVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{17}
}

func (x *GetVmResponse) GetSpec() *VmSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GetVmResponse) GetStatus() *VmStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetVmResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ListVmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNode    string                 `protobuf:"bytes,1,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"` // Optional - list from specific node, or all nodes if empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsRequest) Reset() {
	*x = ListVmsRequest{}
	mi := &file_proto_controller_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsRequest) ProtoMessage() {}

func (x *ListVmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsRequest.ProtoReflect.Descriptor instead.
func (*ListVmsRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{18}
}

func (x *ListVmsRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

type ListVmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VmInfo              `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsResponse) Reset() {
	*x = ListVmsResponse{}
	mi := &file_proto_controller_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsResponse) ProtoMessage() {}

func (x *ListVmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsResponse.ProtoReflect.Descriptor instead.
func (*ListVmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{19}
}

func (x *ListVmsResponse) GetVms() []*VmInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

type VmInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         VmState                `protobuf:"varint,3,opt,name=state,proto3,enum=kcore.controller.VmState" json:"state,omitempty"`
	Cpu           int32                  `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	NodeId        string                 `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Which node it's on
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmInfo) Reset() {
	*x = VmInfo{}
	mi := &file_proto_controller_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmInfo) ProtoMessage() {}

func (x *VmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmInfo.ProtoReflect.Descriptor instead.
func (*VmInfo) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{20}
}

func (x *VmInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmInfo) GetState() VmState {
	if x != nil {
		return x.State
	}
	return VmState_VM_STATE_UNKNOWN
}

func (x *VmInfo) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *VmInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *VmInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *VmInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_proto_controller_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{21}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_proto_controller_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{22}
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Capacity      *NodeCapacity          `protobuf:"bytes,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Usage         *NodeUsage             `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // "ready", "not-ready", "unknown"
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_controller_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{23}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetCapacity() *NodeCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *NodeInfo) GetUsage() *NodeUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInfo) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_proto_controller_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{24}
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_proto_controller_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{25}
}

func (x *GetNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type VmSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cpu              int32                  `protobuf:"varint,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryBytes      int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Disks            []*Disk                `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	Nics             []*Nic                 `protobuf:"bytes,6,rep,name=nics,proto3" json:"nics,omitempty"`
	EnableKcoreLogin bool                   `protobuf:"varint,7,opt,name=enable_kcore_login,json=enableKcoreLogin,proto3" json:"enable_kcore_login,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VmSpec) Reset() {
	*x = VmSpec{}
	mi := &file_proto_controller_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmSpec) ProtoMessage() {}

func (x *VmSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmSpec.ProtoReflect.Descriptor instead.
func (*VmSpec) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{26}
}

func (x *VmSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmSpec) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *VmSpec) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *VmSpec) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *VmSpec) GetNics() []*Nic {
	if x != nil {
		return x.Nics
	}
	return nil
}

func (x *VmSpec) GetEnableKcoreLogin() bool {
	if x != nil {
		return x.EnableKcoreLogin
	}
	return false
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BackendHandle string                 `protobuf:"bytes,2,opt,name=backend_handle,json=backendHandle,proto3" json:"backend_handle,omitempty"`
	Bus           string                 `protobuf:"bytes,3,opt,name=bus,proto3" json:"bus,omitempty"`
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_proto_controller_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{27}
}

func (x *Disk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Disk) GetBackendHandle() string {
	if x != nil {
		return x.BackendHandle
	}
	return ""
}

func (x *Disk) GetBus() string {
	if x != nil {
		return x.Bus
	}
	return ""
}

func (x *Disk) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type Nic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nic) Reset() {
	*x = Nic{}
	mi := &file_proto_controller_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nic) ProtoMessage() {}

func (x *Nic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nic.ProtoReflect.Descriptor instead.
func (*Nic) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{28}
}

func (x *Nic) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Nic) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Nic) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type VmStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         VmState                `protobuf:"varint,2,opt,name=state,proto3,enum=kcore.controller.VmState" json:"state,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmStatus) Reset() {
	*x = VmStatus{}
	mi := &file_proto_controller_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmStatus) ProtoMessage() {}

func (x *VmStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmStatus.ProtoReflect.Descriptor instead.
func (*VmStatus) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{29}
}

func (x *VmStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmStatus) GetState() VmState {
	if x != nil {
		return x.State
	}
	return VmState_VM_STATE_UNKNOWN
}

func (x *VmStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VmStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ApplyNixConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full contents to write to /etc/nixos/configuration.nix
	ConfigurationNix string `protobuf:"bytes,1,opt,name=configuration_nix,json=configurationNix,proto3" json:"configuration_nix,omitempty"`
	// When true, run `nixos-rebuild switch` after writing the file.
	// When false, only write the file.
	Rebuild       bool `protobuf:"varint,2,opt,name=rebuild,proto3" json:"rebuild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyNixConfigRequest) Reset() {
	*x = ApplyNixConfigRequest{}
	mi := &file_proto_controller_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyNixConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyNixConfigRequest) ProtoMessage() {}

func (x *ApplyNixConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyNixConfigRequest.ProtoReflect.Descriptor instead.
func (*ApplyNixConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{30}
}

func (x *ApplyNixConfigRequest) GetConfigurationNix() string {
	if x != nil {
		return x.ConfigurationNix
	}
	return ""
}

func (x *ApplyNixConfigRequest) GetRebuild() bool {
	if x != nil {
		return x.Rebuild
	}
	return false
}

type ApplyNixConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyNixConfigResponse) Reset() {
	*x = ApplyNixConfigResponse{}
	mi := &file_proto_controller_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyNixConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyNixConfigResponse) ProtoMessage() {}

func (x *ApplyNixConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyNixConfigResponse.ProtoReflect.Descriptor instead.
func (*ApplyNixConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_proto_rawDescGZIP(), []int{31}
}

func (x *ApplyNixConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyNixConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_controller_proto protoreflect.FileDescriptor

const file_proto_controller_proto_rawDesc = "" +
	"\n" +
	"\x16proto/controller.proto\x12\x10kcore.controller\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x01\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12:\n" +
	"\bcapacity\x18\x04 \x01(\v2\x1e.kcore.controller.NodeCapacityR\bcapacity\x12\x16\n" +
	"\x06labels\x18\x05 \x03(\tR\x06labels\"J\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"^\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x121\n" +
	"\x05usage\x18\x02 \x01(\v2\x1b.kcore.controller.NodeUsageR\x05usage\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x12SyncVmStateRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12*\n" +
	"\x03vms\x18\x02 \x03(\v2\x18.kcore.controller.VmInfoR\x03vms\"/\n" +
	"\x13SyncVmStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\fNodeCapacity\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\"]\n" +
	"\tNodeUsage\x12$\n" +
	"\x0ecpu_cores_used\x18\x01 \x01(\x05R\fcpuCoresUsed\x12*\n" +
	"\x11memory_bytes_used\x18\x02 \x01(\x03R\x0fmemoryBytesUsed\"\xae\x01\n" +
	"\x0fCreateVmRequest\x12\x1f\n" +
	"\vtarget_node\x18\x01 \x01(\tR\n" +
	"targetNode\x12,\n" +
	"\x04spec\x18\x02 \x01(\v2\x18.kcore.controller.VmSpecR\x04spec\x12\x1b\n" +
	"\timage_uri\x18\x03 \x01(\tR\bimageUri\x12/\n" +
	"\x14cloud_init_user_data\x18\x04 \x01(\tR\x11cloudInitUserData\"q\n" +
	"\x10CreateVmResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12/\n" +
	"\x05state\x18\x03 \x01(\x0e2\x19.kcore.controller.VmStateR\x05state\"G\n" +
	"\x0fDeleteVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1f\n" +
	"\vtarget_node\x18\x02 \x01(\tR\n" +
	"targetNode\",\n" +
	"\x10DeleteVmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x0eStartVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1f\n" +
	"\vtarget_node\x18\x02 \x01(\tR\n" +
	"targetNode\"B\n" +
	"\x0fStartVmResponse\x12/\n" +
	"\x05state\x18\x01 \x01(\x0e2\x19.kcore.controller.VmStateR\x05state\"[\n" +
	"\rStopVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12\x1f\n" +
	"\vtarget_node\x18\x03 \x01(\tR\n" +
	"targetNode\"A\n" +
	"\x0eStopVmResponse\x12/\n" +
	"\x05state\x18\x01 \x01(\x0e2\x19.kcore.controller.VmStateR\x05state\"D\n" +
	"\fGetVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1f\n" +
	"\vtarget_node\x18\x02 \x01(\tR\n" +
	"targetNode\"\x8a\x01\n" +
	"\rGetVmResponse\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.kcore.controller.VmSpecR\x04spec\x122\n" +
	"\x06status\x18\x02 \x01(\v2\x1a.kcore.controller.VmStatusR\x06status\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"1\n" +
	"\x0eListVmsRequest\x12\x1f\n" +
	"\vtarget_node\x18\x01 \x01(\tR\n" +
	"targetNode\"=\n" +
	"\x0fListVmsResponse\x12*\n" +
	"\x03vms\x18\x01 \x03(\v2\x18.kcore.controller.VmInfoR\x03vms\"\xe6\x01\n" +
	"\x06VmInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x05state\x18\x03 \x01(\x0e2\x19.kcore.controller.VmStateR\x05state\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x05R\x03cpu\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\x12\x17\n" +
	"\anode_id\x18\x06 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x12\n" +
	"\x10ListNodesRequest\"E\n" +
	"\x11ListNodesResponse\x120\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1a.kcore.controller.NodeInfoR\x05nodes\"\xa3\x02\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12:\n" +
	"\bcapacity\x18\x04 \x01(\v2\x1e.kcore.controller.NodeCapacityR\bcapacity\x121\n" +
	"\x05usage\x18\x05 \x01(\v2\x1b.kcore.controller.NodeUsageR\x05usage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12A\n" +
	"\x0elast_heartbeat\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\")\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"A\n" +
	"\x0fGetNodeResponse\x12.\n" +
	"\x04node\x18\x01 \x01(\v2\x1a.kcore.controller.NodeInfoR\x04node\"\xe8\x01\n" +
	"\x06VmSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x05R\x03cpu\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes\x12,\n" +
	"\x05disks\x18\x05 \x03(\v2\x16.kcore.controller.DiskR\x05disks\x12)\n" +
	"\x04nics\x18\x06 \x03(\v2\x15.kcore.controller.NicR\x04nics\x12,\n" +
	"\x12enable_kcore_login\x18\a \x01(\bR\x10enableKcoreLogin\"k\n" +
	"\x04Disk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0ebackend_handle\x18\x02 \x01(\tR\rbackendHandle\x12\x10\n" +
	"\x03bus\x18\x03 \x01(\tR\x03bus\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\"V\n" +
	"\x03Nic\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\"\xc1\x01\n" +
	"\bVmStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.kcore.controller.VmStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"^\n" +
	"\x15ApplyNixConfigRequest\x12+\n" +
	"\x11configuration_nix\x18\x01 \x01(\tR\x10configurationNix\x12\x18\n" +
	"\arebuild\x18\x02 \x01(\bR\arebuild\"L\n" +
	"\x16ApplyNixConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*t\n" +
	"\aVmState\x12\x14\n" +
	"\x10VM_STATE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10VM_STATE_STOPPED\x10\x01\x12\x14\n" +
	"\x10VM_STATE_RUNNING\x10\x02\x12\x13\n" +
	"\x0fVM_STATE_PAUSED\x10\x03\x12\x12\n" +
	"\x0eVM_STATE_ERROR\x10\x042\xa0\a\n" +
	"\n" +
	"Controller\x12]\n" +
	"\fRegisterNode\x12%.kcore.controller.RegisterNodeRequest\x1a&.kcore.controller.RegisterNodeResponse\x12T\n" +
	"\tHeartbeat\x12\".kcore.controller.HeartbeatRequest\x1a#.kcore.controller.HeartbeatResponse\x12Z\n" +
	"\vSyncVmState\x12$.kcore.controller.SyncVmStateRequest\x1a%.kcore.controller.SyncVmStateResponse\x12Q\n" +
	"\bCreateVm\x12!.kcore.controller.CreateVmRequest\x1a\".kcore.controller.CreateVmResponse\x12Q\n" +
	"\bDeleteVm\x12!.kcore.controller.DeleteVmRequest\x1a\".kcore.controller.DeleteVmResponse\x12N\n" +
	"\aStartVm\x12 .kcore.controller.StartVmRequest\x1a!.kcore.controller.StartVmResponse\x12K\n" +
	"\x06StopVm\x12\x1f.kcore.controller.StopVmRequest\x1a .kcore.controller.StopVmResponse\x12H\n" +
	"\x05GetVm\x12\x1e.kcore.controller.GetVmRequest\x1a\x1f.kcore.controller.GetVmResponse\x12N\n" +
	"\aListVms\x12 .kcore.controller.ListVmsRequest\x1a!.kcore.controller.ListVmsResponse\x12T\n" +
	"\tListNodes\x12\".kcore.controller.ListNodesRequest\x1a#.kcore.controller.ListNodesResponse\x12N\n" +
	"\aGetNode\x12 .kcore.controller.GetNodeRequest\x1a!.kcore.controller.GetNodeResponse2v\n" +
	"\x0fControllerAdmin\x12c\n" +
	"\x0eApplyNixConfig\x12'.kcore.controller.ApplyNixConfigRequest\x1a(.kcore.controller.ApplyNixConfigResponseB'Z%github.com/kcore/kcore/api/controllerb\x06proto3"

var (
	file_proto_controller_proto_rawDescOnce sync.Once
	file_proto_controller_proto_rawDescData []byte
)

func file_proto_controller_proto_rawDescGZIP() []byte {
	file_proto_controller_proto_rawDescOnce.Do(func() {
		file_proto_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_controller_proto_rawDesc), len(file_proto_controller_proto_rawDesc)))
	})
	return file_proto_controller_proto_rawDescData
}

var file_proto_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_controller_proto_goTypes = []any{
	(VmState)(0),                   // 0: kcore.controller.VmState
	(*RegisterNodeRequest)(nil),    // 1: kcore.controller.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),   // 2: kcore.controller.RegisterNodeResponse
	(*HeartbeatRequest)(nil),       // 3: kcore.controller.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 4: kcore.controller.HeartbeatResponse
	(*SyncVmStateRequest)(nil),     // 5: kcore.controller.SyncVmStateRequest
	(*SyncVmStateResponse)(nil),    // 6: kcore.controller.SyncVmStateResponse
	(*NodeCapacity)(nil),           // 7: kcore.controller.NodeCapacity
	(*NodeUsage)(nil),              // 8: kcore.controller.NodeUsage
	(*CreateVmRequest)(nil),        // 9: kcore.controller.CreateVmRequest
	(*CreateVmResponse)(nil),       // 10: kcore.controller.CreateVmResponse
	(*DeleteVmRequest)(nil),        // 11: kcore.controller.DeleteVmRequest
	(*DeleteVmResponse)(nil),       // 12: kcore.controller.DeleteVmResponse
	(*StartVmRequest)(nil),         // 13: kcore.controller.StartVmRequest
	(*StartVmResponse)(nil),        // 14: kcore.controller.StartVmResponse
	(*StopVmRequest)(nil),          // 15: kcore.controller.StopVmRequest
	(*StopVmResponse)(nil),         // 16: kcore.controller.StopVmResponse
	(*GetVmRequest)(nil),           // 17: kcore.controller.GetVmRequest
	(*GetVmResponse)(nil),          // 18: kcore.controller.GetVmResponse
	(*ListVmsRequest)(nil),         // 19: kcore.controller.ListVmsRequest
	(*ListVmsResponse)(nil),        // 20: kcore.controller.ListVmsResponse
	(*VmInfo)(nil),                 // 21: kcore.controller.VmInfo
	(*ListNodesRequest)(nil),       // 22: kcore.controller.ListNodesRequest
	(*ListNodesResponse)(nil),      // 23: kcore.controller.ListNodesResponse
	(*NodeInfo)(nil),               // 24: kcore.controller.NodeInfo
	(*GetNodeRequest)(nil),         // 25: kcore.controller.GetNodeRequest
	(*GetNodeResponse)(nil),        // 26: kcore.controller.GetNodeResponse
	(*VmSpec)(nil),                 // 27: kcore.controller.VmSpec
	(*Disk)(nil),                   // 28: kcore.controller.Disk
	(*Nic)(nil),                    // 29: kcore.controller.Nic
	(*VmStatus)(nil),               // 30: kcore.controller.VmStatus
	(*ApplyNixConfigRequest)(nil),  // 31: kcore.controller.ApplyNixConfigRequest
	(*ApplyNixConfigResponse)(nil), // 32: kcore.controller.ApplyNixConfigResponse
	(*timestamppb.Timestamp)(nil),  // 33: google.protobuf.Timestamp
}
var file_proto_controller_proto_depIdxs = []int32{
	7,  // 0: kcore.controller.RegisterNodeRequest.capacity:type_name -> kcore.controller.NodeCapacity
	8,  // 1: kcore.controller.HeartbeatRequest.usage:type_name -> kcore.controller.NodeUsage
	21, // 2: kcore.controller.SyncVmStateRequest.vms:type_name -> kcore.controller.VmInfo
	27, // 3: kcore.controller.CreateVmRequest.spec:type_name -> kcore.controller.VmSpec
	0,  // 4: kcore.controller.CreateVmResponse.state:type_name -> kcore.controller.VmState
	0,  // 5: kcore.controller.StartVmResponse.state:type_name -> kcore.controller.VmState
	0,  // 6: kcore.controller.StopVmResponse.state:type_name -> kcore.controller.VmState
	27, // 7: kcore.controller.GetVmResponse.spec:type_name -> kcore.controller.VmSpec
	30, // 8: kcore.controller.GetVmResponse.status:type_name -> kcore.controller.VmStatus
	21, // 9: kcore.controller.ListVmsResponse.vms:type_name -> kcore.controller.VmInfo
	0,  // 10: kcore.controller.VmInfo.state:type_name -> kcore.controller.VmState
	33, // 11: kcore.controller.VmInfo.created_at:type_name -> google.protobuf.Timestamp
	24, // 12: kcore.controller.ListNodesResponse.nodes:type_name -> kcore.controller.NodeInfo
	7,  // 13: kcore.controller.NodeInfo.capacity:type_name -> kcore.controller.NodeCapacity
	8,  // 14: kcore.controller.NodeInfo.usage:type_name -> kcore.controller.NodeUsage
	33, // 15: kcore.controller.NodeInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	24, // 16: kcore.controller.GetNodeResponse.node:type_name -> kcore.controller.NodeInfo
	28, // 17: kcore.controller.VmSpec.disks:type_name -> kcore.controller.Disk
	29, // 18: kcore.controller.VmSpec.nics:type_name -> kcore.controller.Nic
	0,  // 19: kcore.controller.VmStatus.state:type_name -> kcore.controller.VmState
	33, // 20: kcore.controller.VmStatus.created_at:type_name -> google.protobuf.Timestamp
	33, // 21: kcore.controller.VmStatus.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 22: kcore.controller.Controller.RegisterNode:input_type -> kcore.controller.RegisterNodeRequest
	3,  // 23: kcore.controller.Controller.Heartbeat:input_type -> kcore.controller.HeartbeatRequest
	5,  // 24: kcore.controller.Controller.SyncVmState:input_type -> kcore.controller.SyncVmStateRequest
	9,  // 25: kcore.controller.Controller.CreateVm:input_type -> kcore.controller.CreateVmRequest
	11, // 26: kcore.controller.Controller.DeleteVm:input_type -> kcore.controller.DeleteVmRequest
	13, // 27: kcore.controller.Controller.StartVm:input_type -> kcore.controller.StartVmRequest
	15, // 28: kcore.controller.Controller.StopVm:input_type -> kcore.controller.StopVmRequest
	17, // 29: kcore.controller.Controller.GetVm:input_type -> kcore.controller.GetVmRequest
	19, // 30: kcore.controller.Controller.ListVms:input_type -> kcore.controller.ListVmsRequest
	22, // 31: kcore.controller.Controller.ListNodes:input_type -> kcore.controller.ListNodesRequest
	25, // 32: kcore.controller.Controller.GetNode:input_type -> kcore.controller.GetNodeRequest
	31, // 33: kcore.controller.ControllerAdmin.ApplyNixConfig:input_type -> kcore.controller.ApplyNixConfigRequest
	2,  // 34: kcore.controller.Controller.RegisterNode:output_type -> kcore.controller.RegisterNodeResponse
	4,  // 35: kcore.controller.Controller.Heartbeat:output_type -> kcore.controller.HeartbeatResponse
	6,  // 36: kcore.controller.Controller.SyncVmState:output_type -> kcore.controller.SyncVmStateResponse
	10, // 37: kcore.controller.Controller.CreateVm:output_type -> kcore.controller.CreateVmResponse
	12, // 38: kcore.controller.Controller.DeleteVm:output_type -> kcore.controller.DeleteVmResponse
	14, // 39: kcore.controller.Controller.StartVm:output_type -> kcore.controller.StartVmResponse
	16, // 40: kcore.controller.Controller.StopVm:output_type -> kcore.controller.StopVmResponse
	18, // 41: kcore.controller.Controller.GetVm:output_type -> kcore.controller.GetVmResponse
	20, // 42: kcore.controller.Controller.ListVms:output_type -> kcore.controller.ListVmsResponse
	23, // 43: kcore.controller.Controller.ListNodes:output_type -> kcore.controller.ListNodesResponse
	26, // 44: kcore.controller.Controller.GetNode:output_type -> kcore.controller.GetNodeResponse
	32, // 45: kcore.controller.ControllerAdmin.ApplyNixConfig:output_type -> kcore.controller.ApplyNixConfigResponse
	34, // [34:46] is the sub-list for method output_type
	22, // [22:34] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_controller_proto_init() }
func file_proto_controller_proto_init() {
	if File_proto_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_controller_proto_rawDesc), len(file_proto_controller_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_controller_proto_goTypes,
		DependencyIndexes: file_proto_controller_proto_depIdxs,
		EnumInfos:         file_proto_controller_proto_enumTypes,
		MessageInfos:      file_proto_controller_proto_msgTypes,
	}.Build()
	File_proto_controller_proto = out.File
	file_proto_controller_proto_goTypes = nil
	file_proto_controller_proto_depIdxs = nil
}
