// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.4
// source: proto/node.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VM status
type VmState int32

const (
	VmState_VM_STATE_UNKNOWN VmState = 0
	VmState_VM_STATE_STOPPED VmState = 1
	VmState_VM_STATE_RUNNING VmState = 2
	VmState_VM_STATE_PAUSED  VmState = 3
	VmState_VM_STATE_ERROR   VmState = 4
)

// Enum value maps for VmState.
var (
	VmState_name = map[int32]string{
		0: "VM_STATE_UNKNOWN",
		1: "VM_STATE_STOPPED",
		2: "VM_STATE_RUNNING",
		3: "VM_STATE_PAUSED",
		4: "VM_STATE_ERROR",
	}
	VmState_value = map[string]int32{
		"VM_STATE_UNKNOWN": 0,
		"VM_STATE_STOPPED": 1,
		"VM_STATE_RUNNING": 2,
		"VM_STATE_PAUSED":  3,
		"VM_STATE_ERROR":   4,
	}
)

func (x VmState) Enum() *VmState {
	p := new(VmState)
	*p = x
	return p
}

func (x VmState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[0].Descriptor()
}

func (VmState) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[0]
}

func (x VmState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmState.Descriptor instead.
func (VmState) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

// VM specification
type VmSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           int32                  `protobuf:"varint,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Disks         []*Disk                `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	Nics          []*Nic                 `protobuf:"bytes,6,rep,name=nics,proto3" json:"nics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmSpec) Reset() {
	*x = VmSpec{}
	mi := &file_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmSpec) ProtoMessage() {}

func (x *VmSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmSpec.ProtoReflect.Descriptor instead.
func (*VmSpec) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *VmSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmSpec) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *VmSpec) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *VmSpec) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *VmSpec) GetNics() []*Nic {
	if x != nil {
		return x.Nics
	}
	return nil
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BackendHandle string                 `protobuf:"bytes,2,opt,name=backend_handle,json=backendHandle,proto3" json:"backend_handle,omitempty"` // e.g., /dev/vg0/vm-123-root or /path/to/file.qcow2
	Bus           string                 `protobuf:"bytes,3,opt,name=bus,proto3" json:"bus,omitempty"`                                          // virtio, scsi, etc.
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`                                    // vda, sda, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *Disk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Disk) GetBackendHandle() string {
	if x != nil {
		return x.BackendHandle
	}
	return ""
}

func (x *Disk) GetBus() string {
	if x != nil {
		return x.Bus
	}
	return ""
}

func (x *Disk) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type Nic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"` // virtio, e1000, etc.
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nic) Reset() {
	*x = Nic{}
	mi := &file_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nic) ProtoMessage() {}

func (x *Nic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nic.ProtoReflect.Descriptor instead.
func (*Nic) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *Nic) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Nic) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Nic) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type VmStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         VmState                `protobuf:"varint,2,opt,name=state,proto3,enum=kcore.node.VmState" json:"state,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmStatus) Reset() {
	*x = VmStatus{}
	mi := &file_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmStatus) ProtoMessage() {}

func (x *VmStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmStatus.ProtoReflect.Descriptor instead.
func (*VmStatus) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *VmStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmStatus) GetState() VmState {
	if x != nil {
		return x.State
	}
	return VmState_VM_STATE_UNKNOWN
}

func (x *VmStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VmStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateVm
type CreateVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *VmSpec                `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVmRequest) GetSpec() *VmSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *VmStatus              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmResponse) Reset() {
	*x = CreateVmResponse{}
	mi := &file_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse) ProtoMessage() {}

func (x *CreateVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse.ProtoReflect.Descriptor instead.
func (*CreateVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVmResponse) GetStatus() *VmStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// UpdateVm
type UpdateVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *VmSpec                `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVmRequest) Reset() {
	*x = UpdateVmRequest{}
	mi := &file_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVmRequest) ProtoMessage() {}

func (x *UpdateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVmRequest.ProtoReflect.Descriptor instead.
func (*UpdateVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVmRequest) GetSpec() *VmSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type UpdateVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *VmStatus              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVmResponse) Reset() {
	*x = UpdateVmResponse{}
	mi := &file_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVmResponse) ProtoMessage() {}

func (x *UpdateVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVmResponse.ProtoReflect.Descriptor instead.
func (*UpdateVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateVmResponse) GetStatus() *VmStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// DeleteVm
type DeleteVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVmRequest) Reset() {
	*x = DeleteVmRequest{}
	mi := &file_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmRequest) ProtoMessage() {}

func (x *DeleteVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmRequest.ProtoReflect.Descriptor instead.
func (*DeleteVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type DeleteVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVmResponse) Reset() {
	*x = DeleteVmResponse{}
	mi := &file_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmResponse) ProtoMessage() {}

func (x *DeleteVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmResponse.ProtoReflect.Descriptor instead.
func (*DeleteVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{9}
}

// StartVm
type StartVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmRequest) Reset() {
	*x = StartVmRequest{}
	mi := &file_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmRequest) ProtoMessage() {}

func (x *StartVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmRequest.ProtoReflect.Descriptor instead.
func (*StartVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *StartVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StartVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *VmStatus              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmResponse) Reset() {
	*x = StartVmResponse{}
	mi := &file_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmResponse) ProtoMessage() {}

func (x *StartVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmResponse.ProtoReflect.Descriptor instead.
func (*StartVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *StartVmResponse) GetStatus() *VmStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// StopVm
type StopVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmRequest) Reset() {
	*x = StopVmRequest{}
	mi := &file_proto_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmRequest) ProtoMessage() {}

func (x *StopVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmRequest.ProtoReflect.Descriptor instead.
func (*StopVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{12}
}

func (x *StopVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StopVmRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type StopVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *VmStatus              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmResponse) Reset() {
	*x = StopVmResponse{}
	mi := &file_proto_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmResponse) ProtoMessage() {}

func (x *StopVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmResponse.ProtoReflect.Descriptor instead.
func (*StopVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{13}
}

func (x *StopVmResponse) GetStatus() *VmStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// RebootVm
type RebootVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootVmRequest) Reset() {
	*x = RebootVmRequest{}
	mi := &file_proto_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootVmRequest) ProtoMessage() {}

func (x *RebootVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootVmRequest.ProtoReflect.Descriptor instead.
func (*RebootVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{14}
}

func (x *RebootVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *RebootVmRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RebootVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *VmStatus              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebootVmResponse) Reset() {
	*x = RebootVmResponse{}
	mi := &file_proto_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootVmResponse) ProtoMessage() {}

func (x *RebootVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootVmResponse.ProtoReflect.Descriptor instead.
func (*RebootVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{15}
}

func (x *RebootVmResponse) GetStatus() *VmStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// GetVm
type GetVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmRequest) Reset() {
	*x = GetVmRequest{}
	mi := &file_proto_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmRequest) ProtoMessage() {}

func (x *GetVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmRequest.ProtoReflect.Descriptor instead.
func (*GetVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{16}
}

func (x *GetVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type GetVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *VmSpec                `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *VmStatus              `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmResponse) Reset() {
	*x = GetVmResponse{}
	mi := &file_proto_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmResponse) ProtoMessage() {}

func (x *GetVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmResponse.ProtoReflect.Descriptor instead.
func (*GetVmResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{17}
}

func (x *GetVmResponse) GetSpec() *VmSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GetVmResponse) GetStatus() *VmStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// ListVms
type ListVmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsRequest) Reset() {
	*x = ListVmsRequest{}
	mi := &file_proto_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsRequest) ProtoMessage() {}

func (x *ListVmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsRequest.ProtoReflect.Descriptor instead.
func (*ListVmsRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{18}
}

type ListVmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VmInfo              `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsResponse) Reset() {
	*x = ListVmsResponse{}
	mi := &file_proto_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsResponse) ProtoMessage() {}

func (x *ListVmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsResponse.ProtoReflect.Descriptor instead.
func (*ListVmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{19}
}

func (x *ListVmsResponse) GetVms() []*VmInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

type VmInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         VmState                `protobuf:"varint,3,opt,name=state,proto3,enum=kcore.node.VmState" json:"state,omitempty"`
	Cpu           int32                  `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmInfo) Reset() {
	*x = VmInfo{}
	mi := &file_proto_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmInfo) ProtoMessage() {}

func (x *VmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmInfo.ProtoReflect.Descriptor instead.
func (*VmInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{20}
}

func (x *VmInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VmInfo) GetState() VmState {
	if x != nil {
		return x.State
	}
	return VmState_VM_STATE_UNKNOWN
}

func (x *VmInfo) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *VmInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *VmInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CreateVolume
type CreateVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	StorageClass  string                 `protobuf:"bytes,2,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // StorageClass-specific params
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_proto_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{21}
}

func (x *CreateVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *CreateVolumeRequest) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *CreateVolumeRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateVolumeRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type CreateVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendHandle string                 `protobuf:"bytes,1,opt,name=backend_handle,json=backendHandle,proto3" json:"backend_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeResponse) Reset() {
	*x = CreateVolumeResponse{}
	mi := &file_proto_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeResponse) ProtoMessage() {}

func (x *CreateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{22}
}

func (x *CreateVolumeResponse) GetBackendHandle() string {
	if x != nil {
		return x.BackendHandle
	}
	return ""
}

// DeleteVolume
type DeleteVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendHandle string                 `protobuf:"bytes,1,opt,name=backend_handle,json=backendHandle,proto3" json:"backend_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeRequest) Reset() {
	*x = DeleteVolumeRequest{}
	mi := &file_proto_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeRequest) ProtoMessage() {}

func (x *DeleteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteVolumeRequest) GetBackendHandle() string {
	if x != nil {
		return x.BackendHandle
	}
	return ""
}

type DeleteVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeResponse) Reset() {
	*x = DeleteVolumeResponse{}
	mi := &file_proto_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeResponse) ProtoMessage() {}

func (x *DeleteVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeResponse.ProtoReflect.Descriptor instead.
func (*DeleteVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{24}
}

// AttachVolume
type AttachVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendHandle string                 `protobuf:"bytes,1,opt,name=backend_handle,json=backendHandle,proto3" json:"backend_handle,omitempty"`
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	TargetDevice  string                 `protobuf:"bytes,3,opt,name=target_device,json=targetDevice,proto3" json:"target_device,omitempty"` // vda, sda, etc.
	Bus           string                 `protobuf:"bytes,4,opt,name=bus,proto3" json:"bus,omitempty"`                                       // virtio, scsi, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachVolumeRequest) Reset() {
	*x = AttachVolumeRequest{}
	mi := &file_proto_node_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachVolumeRequest) ProtoMessage() {}

func (x *AttachVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachVolumeRequest.ProtoReflect.Descriptor instead.
func (*AttachVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{25}
}

func (x *AttachVolumeRequest) GetBackendHandle() string {
	if x != nil {
		return x.BackendHandle
	}
	return ""
}

func (x *AttachVolumeRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *AttachVolumeRequest) GetTargetDevice() string {
	if x != nil {
		return x.TargetDevice
	}
	return ""
}

func (x *AttachVolumeRequest) GetBus() string {
	if x != nil {
		return x.Bus
	}
	return ""
}

type AttachVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachVolumeResponse) Reset() {
	*x = AttachVolumeResponse{}
	mi := &file_proto_node_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachVolumeResponse) ProtoMessage() {}

func (x *AttachVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachVolumeResponse.ProtoReflect.Descriptor instead.
func (*AttachVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{26}
}

// DetachVolume
type DetachVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendHandle string                 `protobuf:"bytes,1,opt,name=backend_handle,json=backendHandle,proto3" json:"backend_handle,omitempty"`
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachVolumeRequest) Reset() {
	*x = DetachVolumeRequest{}
	mi := &file_proto_node_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachVolumeRequest) ProtoMessage() {}

func (x *DetachVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachVolumeRequest.ProtoReflect.Descriptor instead.
func (*DetachVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{27}
}

func (x *DetachVolumeRequest) GetBackendHandle() string {
	if x != nil {
		return x.BackendHandle
	}
	return ""
}

func (x *DetachVolumeRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type DetachVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachVolumeResponse) Reset() {
	*x = DetachVolumeResponse{}
	mi := &file_proto_node_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachVolumeResponse) ProtoMessage() {}

func (x *DetachVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachVolumeResponse.ProtoReflect.Descriptor instead.
func (*DetachVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{28}
}

// GetNodeInfo
type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_proto_node_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{29}
}

type GetNodeInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Capacity        *NodeCapacity          `protobuf:"bytes,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Usage           *NodeUsage             `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	StorageBackends []*StorageBackend      `protobuf:"bytes,5,rep,name=storage_backends,json=storageBackends,proto3" json:"storage_backends,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_proto_node_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{30}
}

func (x *GetNodeInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetNodeInfoResponse) GetCapacity() *NodeCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *GetNodeInfoResponse) GetUsage() *NodeUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *GetNodeInfoResponse) GetStorageBackends() []*StorageBackend {
	if x != nil {
		return x.StorageBackends
	}
	return nil
}

type NodeCapacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapacity) Reset() {
	*x = NodeCapacity{}
	mi := &file_proto_node_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapacity) ProtoMessage() {}

func (x *NodeCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapacity.ProtoReflect.Descriptor instead.
func (*NodeCapacity) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{31}
}

func (x *NodeCapacity) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeCapacity) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type NodeUsage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuCoresUsed    int32                  `protobuf:"varint,1,opt,name=cpu_cores_used,json=cpuCoresUsed,proto3" json:"cpu_cores_used,omitempty"`
	MemoryBytesUsed int64                  `protobuf:"varint,2,opt,name=memory_bytes_used,json=memoryBytesUsed,proto3" json:"memory_bytes_used,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeUsage) Reset() {
	*x = NodeUsage{}
	mi := &file_proto_node_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUsage) ProtoMessage() {}

func (x *NodeUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUsage.ProtoReflect.Descriptor instead.
func (*NodeUsage) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{32}
}

func (x *NodeUsage) GetCpuCoresUsed() int32 {
	if x != nil {
		return x.CpuCoresUsed
	}
	return 0
}

func (x *NodeUsage) GetMemoryBytesUsed() int64 {
	if x != nil {
		return x.MemoryBytesUsed
	}
	return 0
}

type StorageBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageClass  string                 `protobuf:"bytes,1,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes     int64                  `protobuf:"varint,3,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	Shared        bool                   `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"` // Whether volumes are visible from other nodes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBackend) Reset() {
	*x = StorageBackend{}
	mi := &file_proto_node_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackend) ProtoMessage() {}

func (x *StorageBackend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBackend.ProtoReflect.Descriptor instead.
func (*StorageBackend) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{33}
}

func (x *StorageBackend) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *StorageBackend) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StorageBackend) GetFreeBytes() int64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *StorageBackend) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

var File_proto_node_proto protoreflect.FileDescriptor

const file_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x10proto/node.proto\x12\n" +
	"kcore.node\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\x06VmSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x05R\x03cpu\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes\x12&\n" +
	"\x05disks\x18\x05 \x03(\v2\x10.kcore.node.DiskR\x05disks\x12#\n" +
	"\x04nics\x18\x06 \x03(\v2\x0f.kcore.node.NicR\x04nics\"k\n" +
	"\x04Disk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0ebackend_handle\x18\x02 \x01(\tR\rbackendHandle\x12\x10\n" +
	"\x03bus\x18\x03 \x01(\tR\x03bus\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\"V\n" +
	"\x03Nic\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\"\xbb\x01\n" +
	"\bVmStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.kcore.node.VmStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"9\n" +
	"\x0fCreateVmRequest\x12&\n" +
	"\x04spec\x18\x01 \x01(\v2\x12.kcore.node.VmSpecR\x04spec\"@\n" +
	"\x10CreateVmResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.kcore.node.VmStatusR\x06status\"9\n" +
	"\x0fUpdateVmRequest\x12&\n" +
	"\x04spec\x18\x01 \x01(\v2\x12.kcore.node.VmSpecR\x04spec\"@\n" +
	"\x10UpdateVmResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.kcore.node.VmStatusR\x06status\"&\n" +
	"\x0fDeleteVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x12\n" +
	"\x10DeleteVmResponse\"%\n" +
	"\x0eStartVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"?\n" +
	"\x0fStartVmResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.kcore.node.VmStatusR\x06status\":\n" +
	"\rStopVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\">\n" +
	"\x0eStopVmResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.kcore.node.VmStatusR\x06status\"<\n" +
	"\x0fRebootVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"@\n" +
	"\x10RebootVmResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.kcore.node.VmStatusR\x06status\"#\n" +
	"\fGetVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"e\n" +
	"\rGetVmResponse\x12&\n" +
	"\x04spec\x18\x01 \x01(\v2\x12.kcore.node.VmSpecR\x04spec\x12,\n" +
	"\x06status\x18\x02 \x01(\v2\x14.kcore.node.VmStatusR\x06status\"\x10\n" +
	"\x0eListVmsRequest\"7\n" +
	"\x0fListVmsResponse\x12$\n" +
	"\x03vms\x18\x01 \x03(\v2\x12.kcore.node.VmInfoR\x03vms\"\xc7\x01\n" +
	"\x06VmInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x05state\x18\x03 \x01(\x0e2\x13.kcore.node.VmStateR\x05state\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x05R\x03cpu\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x86\x02\n" +
	"\x13CreateVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12#\n" +
	"\rstorage_class\x18\x02 \x01(\tR\fstorageClass\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12O\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2/.kcore.node.CreateVolumeRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x14CreateVolumeResponse\x12%\n" +
	"\x0ebackend_handle\x18\x01 \x01(\tR\rbackendHandle\"<\n" +
	"\x13DeleteVolumeRequest\x12%\n" +
	"\x0ebackend_handle\x18\x01 \x01(\tR\rbackendHandle\"\x16\n" +
	"\x14DeleteVolumeResponse\"\x88\x01\n" +
	"\x13AttachVolumeRequest\x12%\n" +
	"\x0ebackend_handle\x18\x01 \x01(\tR\rbackendHandle\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12#\n" +
	"\rtarget_device\x18\x03 \x01(\tR\ftargetDevice\x12\x10\n" +
	"\x03bus\x18\x04 \x01(\tR\x03bus\"\x16\n" +
	"\x14AttachVolumeResponse\"Q\n" +
	"\x13DetachVolumeRequest\x12%\n" +
	"\x0ebackend_handle\x18\x01 \x01(\tR\rbackendHandle\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\"\x16\n" +
	"\x14DetachVolumeResponse\"\x14\n" +
	"\x12GetNodeInfoRequest\"\xf4\x01\n" +
	"\x13GetNodeInfoResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x124\n" +
	"\bcapacity\x18\x03 \x01(\v2\x18.kcore.node.NodeCapacityR\bcapacity\x12+\n" +
	"\x05usage\x18\x04 \x01(\v2\x15.kcore.node.NodeUsageR\x05usage\x12E\n" +
	"\x10storage_backends\x18\x05 \x03(\v2\x1a.kcore.node.StorageBackendR\x0fstorageBackends\"N\n" +
	"\fNodeCapacity\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\"]\n" +
	"\tNodeUsage\x12$\n" +
	"\x0ecpu_cores_used\x18\x01 \x01(\x05R\fcpuCoresUsed\x12*\n" +
	"\x11memory_bytes_used\x18\x02 \x01(\x03R\x0fmemoryBytesUsed\"\x8d\x01\n" +
	"\x0eStorageBackend\x12#\n" +
	"\rstorage_class\x18\x01 \x01(\tR\fstorageClass\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x03 \x01(\x03R\tfreeBytes\x12\x16\n" +
	"\x06shared\x18\x04 \x01(\bR\x06shared*t\n" +
	"\aVmState\x12\x14\n" +
	"\x10VM_STATE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10VM_STATE_STOPPED\x10\x01\x12\x14\n" +
	"\x10VM_STATE_RUNNING\x10\x02\x12\x13\n" +
	"\x0fVM_STATE_PAUSED\x10\x03\x12\x12\n" +
	"\x0eVM_STATE_ERROR\x10\x042\xb0\x04\n" +
	"\vNodeCompute\x12E\n" +
	"\bCreateVm\x12\x1b.kcore.node.CreateVmRequest\x1a\x1c.kcore.node.CreateVmResponse\x12E\n" +
	"\bUpdateVm\x12\x1b.kcore.node.UpdateVmRequest\x1a\x1c.kcore.node.UpdateVmResponse\x12E\n" +
	"\bDeleteVm\x12\x1b.kcore.node.DeleteVmRequest\x1a\x1c.kcore.node.DeleteVmResponse\x12B\n" +
	"\aStartVm\x12\x1a.kcore.node.StartVmRequest\x1a\x1b.kcore.node.StartVmResponse\x12?\n" +
	"\x06StopVm\x12\x19.kcore.node.StopVmRequest\x1a\x1a.kcore.node.StopVmResponse\x12E\n" +
	"\bRebootVm\x12\x1b.kcore.node.RebootVmRequest\x1a\x1c.kcore.node.RebootVmResponse\x12<\n" +
	"\x05GetVm\x12\x18.kcore.node.GetVmRequest\x1a\x19.kcore.node.GetVmResponse\x12B\n" +
	"\aListVms\x12\x1a.kcore.node.ListVmsRequest\x1a\x1b.kcore.node.ListVmsResponse2\xd9\x02\n" +
	"\vNodeStorage\x12Q\n" +
	"\fCreateVolume\x12\x1f.kcore.node.CreateVolumeRequest\x1a .kcore.node.CreateVolumeResponse\x12Q\n" +
	"\fDeleteVolume\x12\x1f.kcore.node.DeleteVolumeRequest\x1a .kcore.node.DeleteVolumeResponse\x12Q\n" +
	"\fAttachVolume\x12\x1f.kcore.node.AttachVolumeRequest\x1a .kcore.node.AttachVolumeResponse\x12Q\n" +
	"\fDetachVolume\x12\x1f.kcore.node.DetachVolumeRequest\x1a .kcore.node.DetachVolumeResponse2Z\n" +
	"\bNodeInfo\x12N\n" +
	"\vGetNodeInfo\x12\x1e.kcore.node.GetNodeInfoRequest\x1a\x1f.kcore.node.GetNodeInfoResponseB!Z\x1fgithub.com/kcore/kcore/api/nodeb\x06proto3"

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData []byte
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)))
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_node_proto_goTypes = []any{
	(VmState)(0),                  // 0: kcore.node.VmState
	(*VmSpec)(nil),                // 1: kcore.node.VmSpec
	(*Disk)(nil),                  // 2: kcore.node.Disk
	(*Nic)(nil),                   // 3: kcore.node.Nic
	(*VmStatus)(nil),              // 4: kcore.node.VmStatus
	(*CreateVmRequest)(nil),       // 5: kcore.node.CreateVmRequest
	(*CreateVmResponse)(nil),      // 6: kcore.node.CreateVmResponse
	(*UpdateVmRequest)(nil),       // 7: kcore.node.UpdateVmRequest
	(*UpdateVmResponse)(nil),      // 8: kcore.node.UpdateVmResponse
	(*DeleteVmRequest)(nil),       // 9: kcore.node.DeleteVmRequest
	(*DeleteVmResponse)(nil),      // 10: kcore.node.DeleteVmResponse
	(*StartVmRequest)(nil),        // 11: kcore.node.StartVmRequest
	(*StartVmResponse)(nil),       // 12: kcore.node.StartVmResponse
	(*StopVmRequest)(nil),         // 13: kcore.node.StopVmRequest
	(*StopVmResponse)(nil),        // 14: kcore.node.StopVmResponse
	(*RebootVmRequest)(nil),       // 15: kcore.node.RebootVmRequest
	(*RebootVmResponse)(nil),      // 16: kcore.node.RebootVmResponse
	(*GetVmRequest)(nil),          // 17: kcore.node.GetVmRequest
	(*GetVmResponse)(nil),         // 18: kcore.node.GetVmResponse
	(*ListVmsRequest)(nil),        // 19: kcore.node.ListVmsRequest
	(*ListVmsResponse)(nil),       // 20: kcore.node.ListVmsResponse
	(*VmInfo)(nil),                // 21: kcore.node.VmInfo
	(*CreateVolumeRequest)(nil),   // 22: kcore.node.CreateVolumeRequest
	(*CreateVolumeResponse)(nil),  // 23: kcore.node.CreateVolumeResponse
	(*DeleteVolumeRequest)(nil),   // 24: kcore.node.DeleteVolumeRequest
	(*DeleteVolumeResponse)(nil),  // 25: kcore.node.DeleteVolumeResponse
	(*AttachVolumeRequest)(nil),   // 26: kcore.node.AttachVolumeRequest
	(*AttachVolumeResponse)(nil),  // 27: kcore.node.AttachVolumeResponse
	(*DetachVolumeRequest)(nil),   // 28: kcore.node.DetachVolumeRequest
	(*DetachVolumeResponse)(nil),  // 29: kcore.node.DetachVolumeResponse
	(*GetNodeInfoRequest)(nil),    // 30: kcore.node.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),   // 31: kcore.node.GetNodeInfoResponse
	(*NodeCapacity)(nil),          // 32: kcore.node.NodeCapacity
	(*NodeUsage)(nil),             // 33: kcore.node.NodeUsage
	(*StorageBackend)(nil),        // 34: kcore.node.StorageBackend
	nil,                           // 35: kcore.node.CreateVolumeRequest.ParametersEntry
	(*timestamppb.Timestamp)(nil), // 36: google.protobuf.Timestamp
}
var file_proto_node_proto_depIdxs = []int32{
	2,  // 0: kcore.node.VmSpec.disks:type_name -> kcore.node.Disk
	3,  // 1: kcore.node.VmSpec.nics:type_name -> kcore.node.Nic
	0,  // 2: kcore.node.VmStatus.state:type_name -> kcore.node.VmState
	36, // 3: kcore.node.VmStatus.created_at:type_name -> google.protobuf.Timestamp
	36, // 4: kcore.node.VmStatus.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: kcore.node.CreateVmRequest.spec:type_name -> kcore.node.VmSpec
	4,  // 6: kcore.node.CreateVmResponse.status:type_name -> kcore.node.VmStatus
	1,  // 7: kcore.node.UpdateVmRequest.spec:type_name -> kcore.node.VmSpec
	4,  // 8: kcore.node.UpdateVmResponse.status:type_name -> kcore.node.VmStatus
	4,  // 9: kcore.node.StartVmResponse.status:type_name -> kcore.node.VmStatus
	4,  // 10: kcore.node.StopVmResponse.status:type_name -> kcore.node.VmStatus
	4,  // 11: kcore.node.RebootVmResponse.status:type_name -> kcore.node.VmStatus
	1,  // 12: kcore.node.GetVmResponse.spec:type_name -> kcore.node.VmSpec
	4,  // 13: kcore.node.GetVmResponse.status:type_name -> kcore.node.VmStatus
	21, // 14: kcore.node.ListVmsResponse.vms:type_name -> kcore.node.VmInfo
	0,  // 15: kcore.node.VmInfo.state:type_name -> kcore.node.VmState
	36, // 16: kcore.node.VmInfo.created_at:type_name -> google.protobuf.Timestamp
	35, // 17: kcore.node.CreateVolumeRequest.parameters:type_name -> kcore.node.CreateVolumeRequest.ParametersEntry
	32, // 18: kcore.node.GetNodeInfoResponse.capacity:type_name -> kcore.node.NodeCapacity
	33, // 19: kcore.node.GetNodeInfoResponse.usage:type_name -> kcore.node.NodeUsage
	34, // 20: kcore.node.GetNodeInfoResponse.storage_backends:type_name -> kcore.node.StorageBackend
	5,  // 21: kcore.node.NodeCompute.CreateVm:input_type -> kcore.node.CreateVmRequest
	7,  // 22: kcore.node.NodeCompute.UpdateVm:input_type -> kcore.node.UpdateVmRequest
	9,  // 23: kcore.node.NodeCompute.DeleteVm:input_type -> kcore.node.DeleteVmRequest
	11, // 24: kcore.node.NodeCompute.StartVm:input_type -> kcore.node.StartVmRequest
	13, // 25: kcore.node.NodeCompute.StopVm:input_type -> kcore.node.StopVmRequest
	15, // 26: kcore.node.NodeCompute.RebootVm:input_type -> kcore.node.RebootVmRequest
	17, // 27: kcore.node.NodeCompute.GetVm:input_type -> kcore.node.GetVmRequest
	19, // 28: kcore.node.NodeCompute.ListVms:input_type -> kcore.node.ListVmsRequest
	22, // 29: kcore.node.NodeStorage.CreateVolume:input_type -> kcore.node.CreateVolumeRequest
	24, // 30: kcore.node.NodeStorage.DeleteVolume:input_type -> kcore.node.DeleteVolumeRequest
	26, // 31: kcore.node.NodeStorage.AttachVolume:input_type -> kcore.node.AttachVolumeRequest
	28, // 32: kcore.node.NodeStorage.DetachVolume:input_type -> kcore.node.DetachVolumeRequest
	30, // 33: kcore.node.NodeInfo.GetNodeInfo:input_type -> kcore.node.GetNodeInfoRequest
	6,  // 34: kcore.node.NodeCompute.CreateVm:output_type -> kcore.node.CreateVmResponse
	8,  // 35: kcore.node.NodeCompute.UpdateVm:output_type -> kcore.node.UpdateVmResponse
	10, // 36: kcore.node.NodeCompute.DeleteVm:output_type -> kcore.node.DeleteVmResponse
	12, // 37: kcore.node.NodeCompute.StartVm:output_type -> kcore.node.StartVmResponse
	14, // 38: kcore.node.NodeCompute.StopVm:output_type -> kcore.node.StopVmResponse
	16, // 39: kcore.node.NodeCompute.RebootVm:output_type -> kcore.node.RebootVmResponse
	18, // 40: kcore.node.NodeCompute.GetVm:output_type -> kcore.node.GetVmResponse
	20, // 41: kcore.node.NodeCompute.ListVms:output_type -> kcore.node.ListVmsResponse
	23, // 42: kcore.node.NodeStorage.CreateVolume:output_type -> kcore.node.CreateVolumeResponse
	25, // 43: kcore.node.NodeStorage.DeleteVolume:output_type -> kcore.node.DeleteVolumeResponse
	27, // 44: kcore.node.NodeStorage.AttachVolume:output_type -> kcore.node.AttachVolumeResponse
	29, // 45: kcore.node.NodeStorage.DetachVolume:output_type -> kcore.node.DetachVolumeResponse
	31, // 46: kcore.node.NodeInfo.GetNodeInfo:output_type -> kcore.node.GetNodeInfoResponse
	34, // [34:47] is the sub-list for method output_type
	21, // [21:34] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		EnumInfos:         file_proto_node_proto_enumTypes,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
